replaced symlinks with hardlinks :-)

diff --git a/bin/arduinoserial b/bin/arduinoserial
--- a/bin/arduinoserial
+++ b/bin/arduinoserial
@@ -1,1 +1,62 @@
-../../../bin/arduinoserial
+#!/bin/sh
+
+# MEMO: add current user to dialot to be able to access the serial ports  https://askubuntu.com/questions/133235/how-do-i-allow-non-root-access-to-ttyusb0
+# sudo usermod -a -G dialout $USER
+
+#SPEED=9600
+SPEED=115200
+
+[ -c /dev/ttyUSB0 ] && SERIAL_DEV=/dev/ttyUSB0
+[ -c /dev/ttyUSB1 ] && SERIAL_DEV=/dev/ttyUSB1
+[ -c /dev/ttyUSB2 ] && SERIAL_DEV=/dev/ttyUSB2
+[ -c /dev/ttyACM0 ] && SERIAL_DEV=/dev/ttyACM0
+[ -c /dev/ttyACM1 ] && SERIAL_DEV=/dev/ttyACM1
+[ -c /dev/ttyACM2 ] && SERIAL_DEV=/dev/ttyACM2
+if [ -z "$SERIAL_DEV" ]; then
+	echo "$(basename $0) error: arduino device not found" >&2
+	exit 1
+fi
+
+if [ ! -z "$1" ]; then
+	# TODO: accept args like  https://github.com/todbot/arduino-serial/
+	# single message mode using python
+	sudo python -  <<EOF
+import serial
+import time
+print("opening connection with $SERIAL_DEV @ $SPEED baud...")
+arduino_ser = serial.Serial("$SERIAL_DEV", $SPEED)
+print("ok, sleep for 7 seconds...")
+time.sleep(7)
+print("sending message: $1"+'\n')
+arduino_ser.write("$1"+'\n')
+# TODO: read the answer?
+#arduino_ser.flush()
+EOF
+	exit $?
+fi
+
+echo "arduino-serial: starting terminal mode, press ctrl-x to exit..."
+#some cmds: "setpindir 13 out; writepin 13 0"
+
+# TODO: enable stdin redirection  https://stackoverflow.com/questions/3918032/bash-serial-i-o-and-arduino
+
+busybox microcom -s $SPEED $SERIAL_DEV
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+screen $SERIAL_DEV $SPEED
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+python -m serial.tools.miniterm --raw  $SERIAL_DEV $SPEED
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+# setup parameters from http://playground.arduino.cc/Interfacing/LinuxTTY
+#stty -F $SERIAL_DEV cs8 $SPEED ignbrk -brkint -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts
+# TODO: get settings via $(stty -a < $SERIAL_DEV)
+
+		
+#echo "unable to start an interactive shell, just echo your commands by echo-ing to $SERIAL_DEV" 
+# TODO: elsa shellscript alternative using:
+#  echo $LINE > $SERIAL_DEV
+#  read -dx -t 1 response < $SERIAL_DEV
+#  echo $response
+# MEMO: as a rule, serial ports don't buffer data. If there's no client app to receive the bytes landing on the serial port, they will simply be discarded.  http://unix.stackexchange.com/questions/96718/how-do-i-use-a-serial-port-on-linux-like-a-pipe-or-netcat
diff --git a/bin/extractrun b/bin/extractrun
--- a/bin/extractrun
+++ b/bin/extractrun
@@ -1,1 +1,208 @@
-../../../bin/extractrun
+#!/bin/sh
+
+# Self Extracting PortableLinuxApp by eadmaster
+
+THIS_SCRIPT_DIR="$(dirname $0)"
+#THIS_SCRIPT_DIR="$(dirname $BASH_SOURCE)"
+
+if [ ! -z "$ANDROID_ROOT" ]; then
+	echo "$(basename $0): Android detect, quitting..." >&2
+	exit 1
+fi
+
+[ -z "$PENDRIVE" ] && source $HOME/.profile
+[ -z "$PENDRIVE" ] && export PENDRIVE=/mnt/home
+[ -z "$TMPDIR" ] && export TMPDIR=/tmp  # if not set, TMPDIR is initialized to /tmp
+
+filename="$(basename "$1")"
+#fbname="${filename%.*}"
+fbname=$( echo -n "$filename" | cut -d'.' -f1 )
+
+# TODO: case insensitive matching
+[ -f "$1" ] && ARCHIVENAME="$1"
+[ -f $PENDRIVE/SharedPrograms/$fbname.7z ] && ARCHIVENAME=$PENDRIVE/SharedPrograms/$fbname.7z
+[ -f $PENDRIVE/SharedPrograms/$fbname.zip ] && ARCHIVENAME=$PENDRIVE/SharedPrograms/$fbname.zip
+[ -f $PENDRIVE/PortableLinuxApps/$fbname.7z ] && ARCHIVENAME=$PENDRIVE/PortableLinuxApps/$fbname.7z
+[ -f $PENDRIVE/PortableLinuxApps/$fbname.zip ] && ARCHIVENAME=$PENDRIVE/PortableLinuxApps/$fbname.zip
+[ -f $PENDRIVE/PortableLinuxApps/$fbname.tgz ] && ARCHIVENAME=$PENDRIVE/PortableLinuxApps/$fbname.tgz
+[ -f $PENDRIVE/PortableLinuxApps/cliapps/$fbname.7z ] && ARCHIVENAME=$PENDRIVE/PortableLinuxApps/cliapps/$fbname.7z
+[ -f $PENDRIVE/PortableLinuxApps/cliapps/$fbname.zip ] && ARCHIVENAME=$PENDRIVE/PortableLinuxApps/cliapps/$fbname.zip
+[ -f $PENDRIVE/PortableLinuxApps/cliapps/$fbname.tgz ] && ARCHIVENAME=$PENDRIVE/PortableLinuxApps/cliapps/$fbname.tgz
+[ -f $PENDRIVE/PortableLinuxApps/cliapps/$fbname.gz ] && ARCHIVENAME=$PENDRIVE/PortableLinuxApps/cliapps/$fbname.gz
+[ -f $PENDRIVE/PortableLinuxApps/cliapps/$fbname.bz2 ] && ARCHIVENAME=$PENDRIVE/PortableLinuxApps/cliapps/$fbname.bz2
+[ -f "$THIS_SCRIPT_DIR/$filename.7z" ] && ARCHIVENAME="$THIS_SCRIPT_DIR/$filename.7z"
+#TODO:	find $THIS_SCRIPT_DIR -iname "$filename*.*" -exec export filename=$(basename "{}") \;
+if [ ! -f "$ARCHIVENAME" ]; then
+	echo "$(basename $0) err: archive not found: $fbname.*" >&2
+	exit 127
+fi
+#else
+#echo "$(basename $0) info: archive found: $ARCHIVENAME" >&2
+
+#TODO: check if the archive is encrypted
+#command -p 7z l -slt -- "$ARCHIVENAME" | grep -Fq 'Encrypted = +'  
+ 
+# read password from kde wallet
+export ARCHIVEPASSWORD=$(kwallet-query -f Scripts -r extractrun kdewallet)
+[ -z "$ARCHIVEPASSWORD" ] && export PASSWORD=$(kwalletcli -f Scripts -e extractrun)
+
+# else try to read from a file
+[ -z "$ARCHIVEPASSWORD" ] && [ -f $TMPDIR/r/password ] && export PASSWORD=$(cat $ARCHIVEPASSWORD_FILE)
+
+# else read interactively
+if [ -z "$ARCHIVEPASSWORD" ]; then
+	#echo -n "no password file found, please enter password (will not be echoed): "
+	#read -s PASSWORD
+	#echo -n $ARCHIVEPASSWORD > $ARCHIVEPASSWORD_FILE
+	ARCHIVEPASSWORD=$(zenity --entry --title="Cached password missing" --text="Enter your _password:" --hide-text)  # > $TMPDIR/r/password
+	# if [ $? -eq 1 ]; then ... # The user has either pressed Cancel, or used the window functions to close the dialog.
+	# ALTERNATIVE: kdialog --password "Please enter your password: " > $ARCHIVEPASSWORD_FILE
+	# if [ ! $? -eq 0 ]; then ... # The user has pressed Cancel
+	
+	# save password into the KDE wallet
+	kwalletcli -f "Scripts" -e "extractrun" -p "$ARCHIVEPASSWORD"
+	[ $? -eq 127 ] && echo "$ARCHIVEPASSWORD" | kwallet-query -v -f "Scripts" -w "extractrun"  kdewallet  # not working?
+	
+	# alternative with qdbus  https://nowardev.wordpress.com/2017/01/17/accessing-the-kde-wallet-from-the-command-line-kde-5-version/
+	
+fi
+
+export APPBASEDIR="$TMPDIR/$fbname"
+
+[ ! -d "$APPBASEDIR" ] && mkdir -p "$APPBASEDIR"
+
+if [ ! "$(ls -A $APPBASEDIR)" ]; then
+	# the directory is empty,
+	# we need to extract the archive
+	echo "$(basename $0): extracting $ARCHIVENAME to $APPBASEDIR..." >&2
+	extension=$( echo -n "$ARCHIVENAME" | rev | cut -d'.' -f1 | rev )
+	extension=$( echo -n $extension | tr '[A-Z]' '[a-z]' ) # force lowercase extension
+	if [ "$extension" = "tgz" ]; then
+		tar -C "$APPBASEDIR" -xzf "$ARCHIVENAME"
+	else
+		7z x -aos -o"$APPBASEDIR" -p"$ARCHIVEPASSWORD" "$ARCHIVENAME" > /dev/null  # MEMO: -aos = Skip extracting of existing files. https://sevenzip.osdn.jp/chm/cmdline/switches/overwrite.htm
+		[ $? -eq 127 ] && "$THIS_SCRIPT_DIR/7za" x -o"$APPBASEDIR" -p"$ARCHIVEPASSWORD" "$ARCHIVENAME" > /dev/null
+		# > /dev/null -> MEMO: hides the password prompt
+	fi
+fi
+
+# search for the main EXE
+# MEMO: last has the higher priority:
+if [ -f "$APPBASEDIR/$fbname.exe" ]; then
+	# detect if mono or PE executable -> http://superuser.com/questions/569771/script-test-for-net-or-regular-pe-exe
+	EXEPATH="wine $APPBASEDIR/$fbname.exe"
+	
+	file "$APPBASEDIR/$fbname.exe" | grep -qi ".net"
+	[ $? -eq 0 ] && EXEPATH="mono $APPBASEDIR/$fbname.exe"
+
+	file "$APPBASEDIR/$fbname.exe" | grep -q "DOS"
+	[ $? -eq 0 ] && EXEPATH="dosbox $APPBASEDIR/$fbname.exe"
+fi
+[ -f "$APPBASEDIR/$fbname.jar" ] && EXEPATH="java -jar $APPBASEDIR/$fbname.jar"
+[ -f "$APPBASEDIR/$fbname.py" ] && EXEPATH="python2 $APPBASEDIR/$fbname.py"
+[ -f "$APPBASEDIR/App/usr/bin/$fbname" ] && EXEPATH="$APPBASEDIR/App/usr/bin/$fbname"
+[ -f "$APPBASEDIR/App/bin/$fbname" ] && EXEPATH="$APPBASEDIR/App/bin/$fbname"
+[ -f "$APPBASEDIR/App/$fbname" ] && EXEPATH="$APPBASEDIR/App/$fbname"
+[ -f "$APPBASEDIR/App/$fbname.bin" ] && EXEPATH="$APPBASEDIR/App/$fbname.bin"
+[ -f "$APPBASEDIR/bin/$fbname" ] && EXEPATH="$APPBASEDIR/bin/$fbname"
+[ -f "$APPBASEDIR/$fbname" ] && EXEPATH="$APPBASEDIR/$fbname"
+[ -f "$APPBASEDIR/$fbname.x86" ] && EXEPATH="$APPBASEDIR/$fbname.x86"
+[ -f "$APPBASEDIR/$fbname.sh" ] && EXEPATH="$APPBASEDIR/$fbname.sh"
+[ -f "$APPBASEDIR/${fbname}Portable.sh" ] && EXEPATH="$APPBASEDIR/${fbname}Portable.sh"
+# TODO: uppercase first letter
+
+# try to find the executable using find
+[ -z "$EXEPATH" ] && EXEPATH=$(find $APPBASEDIR -maxdepth 1  -iname ${fbname}* -type f -perm /u=x,g=x,o=x -print | head -n1 )
+#[ -z "$EXEPATH" ] && EXEPATH=wine $(find $APPBASEDIR -iname "$fbname.exe" -type f -perm /u=x,g=x,o=x -print | head -n1 )
+
+# check if $EXEPATH is not defined
+if [ -z "$EXEPATH" ]; then
+	echo "$(basename $0) err: main exe not found" >&2
+	exit 127
+fi
+#else
+#echo "$(basename $0): launching main exe: $EXEPATH"
+
+# make sure the executable flag is set
+if [ -f "$EXEPATH" ]; then
+	chmod u+x $EXEPATH
+fi
+
+#change dir
+#OLDDIR=`pwd`
+#cd $APPBASEDIR
+
+# TODO? mount unionfs ro /root -> $APPBASEDIR/Data
+
+[ ! -d $HOME ] || mkdir -p $APPBASEDIR/Data
+#[ ! -d $APPBASEDIR/Data/.kde ] && ln -sn $HOME/.kde $APPBASEDIR/Data/.kde  2>/dev/null   2FIX: keepass do not start  with this
+#export KDEHOME=$HOME/.kde
+[ ! -d $APPBASEDIR/Data/.fonts ] && ln -sn $HOME/.fonts $APPBASEDIR/Data/.fonts  2>/dev/null
+#[ ! -f $APPBASEDIR/Data/.alsoftrc ] && ln -sn $HOME/.openalrc $APPBASEDIR/Data/.alsoftrc  2>/dev/null
+#[ ! -f $APPBASEDIR/Data/.openalrc ] && ln -sn $HOME/.openalrc $APPBASEDIR/Data/.openalrc  2>/dev/null
+#[ ! -d $APPBASEDIR/Data/.pulse ] && ln -sn $HOME/.pulse $APPBASEDIR/Data/.pulse  2>/dev/null
+#[ ! -d $APPBASEDIR/Data/.pulse ] && cp -r $HOME/.pulse $APPBASEDIR/Data/.pulse  2>/dev/null
+#[ ! -f $APPBASEDIR/Data/.pulse-cookie ] && ln -sn $HOME/.pulse-cookie $APPBASEDIR/Data/.pulse-cookie  2>/dev/null
+#export PULSE_CONFIG_PATH=$APPBASEDIR/Data/.pulse-cookie
+export WINEPREFIX=$HOME/.wine
+#[ ! -d $APPBASEDIR/Data/.fltk ] && cp -r $HOME/.fltk $APPBASEDIR/Data/.fltk  2>/dev/null
+[ ! -f $APPBASEDIR/Data/.gtkrc-2.0 ] && ln -s $HOME/.gtkrc-2.0 $APPBASEDIR/Data/.gtkrc-2.0  2>/dev/null
+[ ! -f $APPBASEDIR/Data/.gtkrc.mine ] && ln -s $HOME/.gtkrc.mine $APPBASEDIR/Data/.gtkrc.mine  2>/dev/null
+[ ! -f $APPBASEDIR/Data/.gtk-bookmarks ] && ln -s $HOME/.gtk-bookmarks $APPBASEDIR/Data/.gtk-bookmarks  2>/dev/null
+#export GTK_???=$HOME
+#export GNOME_HOME=$HOME
+# TODO: override GTK g_get_home_dir -> nsswitch http://unix.stackexchange.com/questions/81670/overriding-home-location/81697
+
+[ -d $APPBASEDIR/App/bin ] && export PATH=$APPBASEDIR/App/bin:$PATH
+[ -d $APPBASEDIR/bin ] && export PATH=$APPBASEDIR/bin:$PATH
+#[ -d $APPBASEDIR/App/lib ] && export LD_LIBRARY_PATH=$APPBASEDIR/App/lib:$LD_LIBRARY_PATH
+#[ -d $APPBASEDIR/lib ] && export LD_LIBRARY_PATH=$APPBASEDIR/lib:$LD_LIBRARY_PATH
+#[ -d $APPBASEDIR/App/LIBS ] && export LD_LIBRARY_PATH=$APPBASEDIR/App/LIBS:$LD_LIBRARY_PATH
+export LD_LIBRARY_PATH=$APPBASEDIR:$APPBASEDIR/App/lib:$APPBASEDIR/lib:$APPBASEDIR/App/LIBS:$LD_LIBRARY_PATH
+export HOME=$APPBASEDIR/Data
+export XDG_DATA_HOME=$APPBASEDIR/Data
+export XDG_CONFIG_HOME=$APPBASEDIR/Data
+#export XDG_CACHE_HOME=$APPBASEDIR/Data
+export XDG_CACHE_HOME=$TMPDIR
+export XDG_DATA_DIRS=$APPBASEDIR/App/usr/share:$APPBASEDIR/usr/share:$XDG_DATA_DIRS
+export XDG_CONFIG_DIRS=$APPBASEDIR/Data:$XDG_CONFIG_DIRS
+export XDG_RUNTIME_DIR=$TMPDIR
+
+# redirect the "/usr" dir using proot (http://proot.me/)
+#[ -d $APPBASEDIR/App/usr/share/$fbname ] && EXEPATH="proot -b $APPBASEDIR/App/usr/share/$fbname:/usr/share/$fbname $EXEPATH"
+#[ -d $APPBASEDIR/usr/share/$fbname ] && EXEPATH="proot -b $APPBASEDIR/usr/share/$fbname:/usr/share/$fbname $EXEPATH"
+#[ -d $APPBASEDIR/usr ] && EXEPATH="proot $(cd $APPBASEDIR/usr; find -type f -printf " -b $APPBASEDIR/usr/%p:/usr/%p" ) $EXEPATH"
+#[ -d $APPBASEDIR/App/usr ] && EXEPATH="proot $(cd $APPBASEDIR/App/usr; find -type f -printf " -b $APPBASEDIR/App/usr/%p:/usr/%p" ) $EXEPATH"
+#[ -d $APPBASEDIR/App/share ] ...
+
+[ -f $APPBASEDIR/_MEMO.txt ] && xdg-open $APPBASEDIR/_MEMO.txt
+[ -f $PENDRIVE/Documents/note/app/$fbname ] && xdg-open $PENDRIVE/Documents/note/app/$fbname.txt
+
+shift
+
+#echo "$(basename $0): launching $EXEPATH $@..." >&2
+#echo
+
+$EXEPATH "$@"
+_EXITSTATUS=$?
+
+# change the exit status for interpreted scripts
+#case $EXEPATH in python*)
+#	["$_EXITSTATUS" -eq 1 ] && exit 127
+#esac
+
+exit $_EXITSTATUS
+
+# start the process detached from the console http://superuser.com/questions/177218/how-to-start-gui-linux-programs-from-the-command-line-but-separate-from-the-com
+#if [[ $ARCHIVENAME = *cliapps* ]]; then
+	# CLI app: do not detach from console
+#	($EXEPATH "$@")
+#else
+	# GUI app: detach from console
+	#($EXEPATH "$@" &)
+#	cd $APPBASEDIR
+#	nohup $EXEPATH "$@" >/dev/null 2>&1&  # doesn't create nohup.out
+#fi
+
+#cd $OLDDIR
+# exit $?
diff --git a/bin/fallocate b/bin/fallocate
--- a/bin/fallocate
+++ b/bin/fallocate
@@ -1,1 +1,29 @@
-../../../bin/fallocate
+#!/bin/sh
+
+command -p fallocate "$@"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+# else alternative using truncate or dd
+
+# args checking
+if [ "$#" -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) OUTPUT_FILENAME -l OUTPUT_FILESIZE[KMG]"
+	echo
+	exit 0
+fi
+if [ -f "$1" ]; then
+	echo "$(basename $0) error: file already exist: $1" >&2
+	exit 1
+fi
+
+echo "$(basename $0): creating new empty file $SIZE bytes big: $OUTPUTFILE"
+
+truncate -s $SIZE "$OUTPUTFILE"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+dd if=/dev/zero of="$OUTPUTFILE" bs=$2 count=1
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+# else
+echo "$(basename $0) error: cannot create file: $1" >&2
+exit 1
diff --git a/bin/filecat b/bin/filecat
--- a/bin/filecat
+++ b/bin/filecat
@@ -1,1 +1,84 @@
-../../../bin/filecat
+#!/bin/sh
+ 
+# args checking
+if [ "$#" -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) INPUT_FILE1 INPUT_FILE2 [...] OUTPUT_FILE"
+	echo
+	exit 1
+elif [ ! -f "$1" ]; then
+	echo "$(basename $0) error: file does not exist: $1" >&2
+	exit 1
+fi
+
+INPUTFILE="$1"
+INPUTFILEEXT=$( echo -n "$INPUTFILE" | rev | cut -d'.' -f1 | rev )
+INPUTFILEEXT=$( echo -n $INPUTFILEEXT | tr '[A-Z]' '[a-z]' ) # force lowercase extension
+INPUTFILENAME="`basename \"$INPUTFILE\" | rev | cut -d'.' -f2- | rev`"
+INPUTFILETYPE=$( file -b -i "$INPUTFILE" | cut -d';' -f1 )
+
+# get the last passed arg (portable way)
+#for OUTPUTFILE; do : ; done
+eval OUTPUTFILE=\$$#
+# check if outputfile not specified
+if [ "$OUTPUTFILE" = "$2" ]; then
+	OUTPUTFILE="${INPUTFILENAME}_merged.$INPUTFILEEXT"
+	INPUT_FILES="$@"
+else
+	INPUT_FILES="${*%${!#}}"
+fi
+
+# TODO: fix spaces in INPUT_FILES
+
+OUTPUTFILEEXT=$( echo -n "$OUTPUTFILE" | rev | cut -d'.' -f1 | rev )
+OUTPUTFILEEXT=$( echo -n $OUTPUTFILEEXT | tr '[A-Z]' '[a-z]' ) # force lowercase extension
+
+echo "creating $OUTPUTFILE from $INPUT_FILES"
+
+case $INPUTFILETYPE in
+	image/* )
+		if [ "$OUTPUTFILEEXT" = "pdf" ] || [ "$OUTPUTFILEEXT" = "tif" ] || [ "$OUTPUTFILEEXT" = "tiff" ]; then
+			# generate an ebook from images with lossless compression
+			imconvert $INPUT_FILES -compress zip "$OUTPUTFILE"
+			exit $?
+		else
+			# concatenate the images in a square table
+			imconvert $INPUT_FILES -append "$OUTPUTFILE"
+			# -append = append vertically
+			# +append = append horizontally
+			# -gravity Center 
+			exit $?
+		fi
+		;;
+	
+	audio/* | video/* ) 
+		# TODO: detect files with the same/different codec https://trac.ffmpeg.org/wiki/Concatenate
+		# TODO: test input and output files have the same extension
+		{ for f in $INPUT_FILES; do echo "file '$(realpath "$f")'"; done } > "$TMPDIR/$$_list.txt"
+		ffmpeg -f concat -safe 0 -i "$TMPDIR/$$_list.txt" -c copy "$OUTPUTFILE"
+		rm "$TMPDIR/$$_list.txt"
+		exit $?
+		;;
+		
+	application/pdf )
+		pdftk $INPUT_FILES cat output "$OUTPUTFILE"
+		_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		pdfunite $INPUT_FILES "$OUTPUTFILE"
+		exit $?
+		;;
+	
+	image/vnd.djvu | image/x.djvu | image/x-djvu )
+		djvm -c "$OUTPUTFILE" $INPUT_FILES
+		exit $?
+		;;
+	
+	# WANTED: source code amalgamation tools
+	
+	text/* )
+		cat $INPUT_FILES > "$OUTPUTFILE"
+		exit $?
+		;;
+
+esac
+
+echo "$(basename $0) error: filetype not supported: $INPUTFILE ($INPUTFILETYPE)" >&2
+exit 1
diff --git a/bin/filecheck b/bin/filecheck
--- a/bin/filecheck
+++ b/bin/filecheck
@@ -1,1 +1,281 @@
-../../../bin/filecheck
+#!/bin/sh
+
+# args checking
+if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) INPUT_FILE"
+	echo
+	exit 0
+elif [ -z "$1" ] || [ "$1" = "-" ]; then
+	echo "$(basename $0) warn: reading input file from stdin" >&2
+	INPUTFILE="$TMPDIR/$$.tmp"
+	cat > $INPUTFILE
+elif [ ! -f "$1" ]; then
+	echo "$(basename $0) error: file does not exist: $1" >&2
+	exit 1
+elif [ ! -z "$2" ]; then
+	# iterate over passed args and recursive call
+	for CURR_FILE in "$@"
+	do
+		echo -n "$(basename $0): checking $CURR_FILE... " >&2
+		$0 "$CURR_FILE"
+		[ $? -eq 0 ] && echo "OK"
+	done
+	exit $?
+fi
+
+# TODO: if [ ! -z "$2" ]; then
+# invoke "$0" recursively
+#fi
+
+INPUTFILE="$1"
+INPUTFILEEXT=$( echo -n "$INPUTFILE" | rev | cut -d'.' -f1 | rev )
+INPUTFILEEXT=$( echo -n $INPUTFILEEXT | tr '[A-Z]' '[a-z]' ) # force lowercase extension
+
+# try to detect the input file type using file
+INPUTFILETYPE=$( file -b -i "$INPUTFILE" | cut -d';' -f1 )
+
+# try to detect the input file type according on its extension (useful if file is missing or buggy)
+case $INPUTFILEEXT in
+	jpg|gif|png|tiff|tif|bmp|xpm|pbm|pgm|ppm|tga|ico|dng|crw ) INPUTFILETYPE=image/$INPUTFILEEXT ;;
+	avi|mkv|ogm|mpg|mpeg|mp4|mp3|mp2|ogg|flac|aac|ac3|a52|dts|asf|rm|wav ) INPUTFILETYPE=video/$INPUTFILEEXT ;;
+	xml ) INPUTFILETYPE=application/xml ;;
+	json ) INPUTFILETYPE=application/json ;;
+	html|htm ) INPUTFILETYPE=text/html ;;
+	c|cpp|h|hpp ) INPUTFILETYPE=text/x-c ;;
+	java ) INPUTFILETYPE=text/x-java ;;
+	php ) INPUTFILETYPE=text/x-php ;;
+	py ) INPUTFILETYPE=text/x-python ;;
+	js ) INPUTFILETYPE=application/javascript ;;
+	xml ) INPUTFILETYPE=application/xml ;;
+	txt ) INPUTFILETYPE=text/plain ;;
+	so ) INPUTFILETYPE=application/x-sharedlib ;;
+	sh ) INPUTFILETYPE=text/x-shellscript ;;
+esac
+
+# TODO: check if filename contains "[+]"
+# check crc32 sum embedded in the filename
+#rhash --check-embedded "$INPUTFILE"
+echo
+
+# look for a specific tool in the system (e.g. mp3check)
+CUSTOMTOOLPATH=$( findcommand ${INPUTFILEEXT}check | head -n1 )
+[ -z "$CUSTOMTOOLPATH" ] && CUSTOMTOOLPATH=$( findcommand ${INPUTFILEEXT}lint | head -n1 )
+if [ ! -z "$CUSTOMTOOLPATH" ]; then
+	$CUSTOMTOOLPATH "$INPUTFILE"
+fi
+
+# switch by input file extension
+case "$INPUTFILEEXT" in
+
+	#mid|midi|kar|mod|xm|s3m|stm|it )
+		#	timidity -Ol "$INPUTFILE"
+		#	exit $?
+	
+	#rtf|odt|odp|odg|ods|doc|xls|mdb|docx|pptx|xlsx|csv|tsv|dbf|txt ) # office
+	#	soffice --norestore ...
+
+	rar )
+		unrar t "$INPUTFILE"
+		_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		#;&  # else fallthru
+		;;
+
+	zip|rar|7z|arj|bz2|cab|cpio|gz|lha|lzh|tar|tgz|tbz|wim|iso|img|ima|vhd|vmdk|vdi|ext2|apk )
+		7z t -bb1 -slt "$INPUTFILE"
+		exit $?
+		;;
+
+	qcow|qcow2|vdi|qed )
+		qemu-img check  --output=human "$INPUTFILE"
+		exit $?
+		;;
+
+	par2 ) 
+		par2 v "$INPUTFILE"
+		exit $?
+		;;
+	
+	smc|sfc|fig|gb|gbc|gba|nds|n64|z64|smd|gen|md|32x|pce|nes|fds|sms|gg|ws|wsc|jag|ngp|ngc|vb )
+		ucon64 "$INPUTFILE"
+		exit $?
+		;;
+		
+	crc|crc32|sfv|md5|ed2k|emulecollection|hash )
+		rhash -c "$INPUTFILE"
+		exit $?
+		;;
+	
+	pgp|sig|asc|sign ) # signature files
+		gpg --verbose --verify "$INPUTFILE" 2>& 1 | grep --color=always -e "^" -e '.*signature from.*'
+		# ALTERNATIVE: openssl (req. certificate path?)
+		exit $?
+		;;
+	
+	key | pem )  # rsa public/private keys
+		openssl rsa -in "$INPUTFILE" check
+		exit $?
+		;;
+	
+	p7m )
+		openssl smime -verify -in "$INPUTFILE" -inform der -CAfile $SSL_CERT_FILE  # -signer $SSL_CERT_FILE 
+		# TODO: fix
+		exit $?
+		;;
+		
+	csv|tsv|isv )  # comma-separated-value (not detected correctly by file?)
+		csvclean -n "$INPUTFILE"
+		csvtool check "$INPUTFILE"
+		exit $?
+		;;
+
+	db ) # BSD dbm
+		db_verify "$INPUTFILE"
+		exit $?
+		;;
+		
+	mp3 )
+		mp3val "$INPUTFILE"
+		_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		;;
+		
+	flac )
+		flac --test "$INPUTFILE"  # --silent 
+		#_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		
+		WAVETMPFILE=/tmp/fakeflac_$$.wav
+		ffmpeg -v quiet -i "$INPUTFILE" -acodec pcm_s16le -f wav $WAVETMPFILE
+		auCDtect $WAVETMPFILE
+		#BUGGY: ffmpeg -v quiet -i "$INPUTFILE" -acodec pcm_s16le -f wav pipe:1 | auCDtect --
+		#fakeflac "$INPUTFILE"
+		rm $WAVETMPFILE
+		exit $?
+		;;
+
+	# TODO: custom xml documents formats: sgml|xsd|xsl|opml|kml|poi|wis|nzb )
+	
+	ps2 )
+		mymcplus "$INPUTFILE" check
+		exit $?
+		;;
+esac
+
+
+# switch by input file mime type
+case "$INPUTFILETYPE" in
+	image* )
+		echo "$(basename $0) info: check if upscaled..."
+		# using resdet  https://github.com/0x09/resdet
+		resdet "$INPUTFILE"
+		echo "$(basename $0) info: if no error is shown then probably the file is fine" >&2
+		identify -verbose -regard-warnings "$INPUTFILE" > /dev/null
+		_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		imconvert "$INPUTFILE" /dev/null
+		_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		ffmpeg -hide_banner -v error -i "$INPUTFILE" -f null -
+		exit $?
+		;;
+	
+	video*|audio* )
+		echo "$(basename $0) info: if no error is shown then probably the file is fine" >&2
+		ffmpeg -hide_banner -v error -i "$INPUTFILE" -f null -
+		_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		mplayer -ao null -vo null -fps 9999999 -msglevel all=1 "$INPUTFILE"
+		exit $?
+		;;
+	
+	application/pdf )
+		qpdf --check  "$INPUTFILE"
+		# TODO: alternative from poppler-utils https://superuser.com/questions/580887/check-if-pdf-files-are-corrupted-using-command-line-on-linux
+		# check pdf signatures via poppler-utils
+		pdfsig "$INPUTFILE"
+		exit $?
+		;;
+
+	text/x-shellscript )
+		checkbashisms "$INPUTFILE"
+		shellcheck "$INPUTFILE"
+		export POSIXLY_CORRECT=1
+		sh -n "$INPUTFILE"
+		exit 0
+		;;
+
+	text/x-c* ) # c-like source code
+		lint "$INPUTFILE"
+		#splint "$INPUTFILE"
+		cppcheck "$INPUTFILE"
+		#oclint "$INPUTFILE"
+		#rats "$INPUTFILE"
+		clang-tidy "$INPUTFILE"
+		gcc -Wall -Wextra -pedantic -Wundef -Wshadow -Winit-self -o NUL -c "$INPUTFILE" > /dev/null
+		exit $?
+		;;
+	
+	text/x-java )
+		jlint "$INPUTFILE"
+		checkstyle "$INPUTFILE"
+		# not working with jdk 1.8? http://stackoverflow.com/questions/20689204/is-there-any-way-to-run-javac-turning-off-code-generation
+		javac -proc:only "$INPUTFILE"
+		javac -d /dev/null "$INPUTFILE"
+		exit $?
+		;;
+	
+	text/x-php )
+		php -l "$INPUTFILE"
+		exit $?
+		;;
+
+	text/x-python | text/python )  # python source code
+		pep8 "$INPUTFILE"
+		pyflakes "$INPUTFILE"
+		pylint --errors-only "$INPUTFILE"
+		flake8 "$INPUTFILE"
+		#python -m "$INPUTFILE"
+		python -d "$INPUTFILE"  # shorter output
+		exit $?
+		;;
+	
+	application/json )
+		# jsonlint from python-demjson
+		jsonlint "$INPUTFILE"
+		#echo "$(basename $0) info: if no error is shown then probably the file is fine" >&2
+		python -m json.tool "$INPUTFILE"  > /dev/null
+		#exit $?
+		;;
+		#;&  # fallthru
+
+	application/javascript | text/javascript )  # javascript source code
+		jslint "$INPUTFILE"
+		jshint "$INPUTFILE"
+		node -c "$INPUTFILE"
+		exit $?
+		;;
+
+	text/html )
+		tidy -e "$INPUTFILE"
+		xmllint --html --noout "$INPUTFILE" > /dev/null
+		# TODO: alternative using python  http://stackoverflow.com/questions/11001996/python-parse-html-files-in-a-directory-and-check-if-they-are-badly-formed
+		exit $?
+		;;
+		
+	application/xml )
+		xmllint --noout "$INPUTFILE"
+		xml val --net -e "$INPUTFILE"
+		xmlstarlet val --net -e "$INPUTFILE"
+		# TODO: alternative using python http://stackoverflow.com/questions/13742538/how-to-validate-xml-using-python-without-third-party-libs
+		exit $?
+		;;
+		
+	text/plain )  # plaintext: check mispelled words
+		echo "$(basename $0) info: mispelled words found:" >&2
+		hunspell -l -d en_US,en-US,it-IT "$INPUTFILE"  # -l -L -w 
+		_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		aspell list < "$INPUTFILE"   # --data-dir=$DICPATH --ignore=3 --dont-backup --ignore-case --dont-ignore-case --lang=en
+		#MORE ALTERNATIVES: ispell
+		# TODO: alternative: split text by words and search them in an external dict from /p/Documents/db/dict/*.dic.gz
+		# TODO: check newlines and encoding inconsistencies
+		exit $?
+		;;
+esac
+
+echo "$(basename $0): extension \"$INPUTFILEEXT\" not supported" >&2
+exit 1
diff --git a/bin/filecmp b/bin/filecmp
--- a/bin/filecmp
+++ b/bin/filecmp
@@ -1,1 +1,115 @@
-../../../bin/filecmp
+#!/bin/sh
+
+# compare 2 files, ignoring tags and (lossless) compression
+
+# args checking
+if [ "$#" -lt 2 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) FILE1 FILE2"
+	echo "returns: 0 if FILE1 and FILE2 have the same contents, 1 if they differ, 2 on errors."
+	exit 0
+elif [ ! -f "$1" ]; then
+	echo "$(basename $0) error: file does not exist: $1" >&2
+	exit 1
+elif [ ! -f "$2" ]; then
+	echo "$(basename $0) error: file does not exist: $2" >&2
+	exit 1
+fi
+
+INPUTFILE="$1"
+INPUTFILEEXT=$( echo -n "$INPUTFILE" | rev | cut -d'.' -f1 | rev )
+INPUTFILEEXT=$( echo -n $INPUTFILEEXT | tr '[A-Z]' '[a-z]' ) # force lowercase extension
+INPUTFILETYPE=$( file -b -i "$INPUTFILE" | cut -d';' -f1 )
+
+INPUTFILE2="$2"
+INPUTFILE2EXT=$( echo -n "$INPUTFILE2" | rev | cut -d'.' -f1 | rev )
+INPUTFILE2EXT=$( echo -n $INPUTFILEEXT2 | tr '[A-Z]' '[a-z]' ) # force lowercase extension
+INPUTFILE2TYPE=$( file -b -i "$INPUTFILE2" | cut -d';' -f1 )
+
+#if [ "$INPUTFILETYPE" != "$INPUTFILE2TYPE" ]; then
+#	echo "$(basename $0) error: cannot compare files of different types: $INPUTFILETYPE and $INPUTFILE2TYPE" >&2
+#	exit 1
+#fi
+
+case $INPUTFILETYPE in
+	image/* )
+		DIFF_PIXELS=$( compare -metric AE "$INPUTFILE" "$INPUTFILE2" null: )
+		if [ -z "$DIFF_PIXELS" ]; then
+			echo "$(basename $0) error: imagemagick not found" >&2
+			exit 2
+		elif [ "$DIFF_PIXELS" -eq "0" ]; then
+			echo "$(basename $0): $INPUTFILE and $INPUTFILE2 have the same contents"  >&2
+			exit 0
+		else
+			echo "$(basename $0): $INPUTFILE and $INPUTFILE2 differ: $DIFF_PIXELS different pixels"
+			exit 1
+		fi
+		;;
+	
+	audio/x-flac )
+		HASH1=$(metaflac --show-md5sum "$INPUTFILE")
+		# MEMO: if metaflac is not found HASH1 will remain empty
+		HASH2=$(metaflac --show-md5sum "$INPUTFILE2")
+		;;  # MEMO: intentional fall-through
+	
+	#TODO: audio/mpeg ) extract crc-16 from "LAME Tag"
+	#
+	
+	audio/* )
+		HASH1=$(shntool md5 "$INPUTFILE")
+		HASH2=$(shntool md5 "$INPUTFILE2")
+		# ALTERNATIVE: sndfile-cmp
+		;; # MEMO: intentional fall-through
+
+	video/* )
+		HASH1=$(ffmpeg -i "$INPUTFILE" -f crc - 2>/dev/null | grep CRC)
+		HASH2=$(ffmpeg -i "$INPUTFILE2" -f crc - 2>/dev/null | grep CRC)
+		;;
+
+	#text/* )
+	#	diff -qs "$INPUTFILE" "$INPUTFILE2"
+	#	exit $?
+	#	;;
+esac
+
+case $INPUTFILEEXT in
+	gz|xz|bz2|lz ) # untested
+		zcmp "$INPUTFILE" "$INPUTFILE2"
+		continue
+		;;
+	zip ) # untested
+		zipcmp "$INPUTFILE" "$INPUTFILE2"
+		continue
+		;;
+	#TODO: zip|rar|7z )
+	#	# HASH1="$(7z l -slt "$INPUTFILE")"
+	#	# HASH2="$(7z l -slt "$INPUTFILE2")"
+	#   # MEMO: need alphabetic sorting
+	#	#continue
+	#	;;
+	pem ) 
+		HASH1=$(openssl x509 -noout -modulus -in "$INPUTFILE")
+		HASH2=$(openssl x509 -noout -modulus -in "$INPUTFILE2")
+esac
+
+if [ -z "$HASH1" ]; then
+	echo "$(basename $0) error: unable to hash: $INPUTFILE" >&2
+	exit 2
+fi
+if [ -z "$HASH2" ]; then
+	echo "$(basename $0) error: unable to hash: $INPUTFILE2" >&2
+	exit 2
+fi
+
+# compare the hashes
+if [ "$HASH1" = "$HASH2" ]; then
+	echo "$(basename $0): $INPUTFILE and $INPUTFILE2 have the same contents"  >&2
+	exit 0
+else
+	echo "$(basename $0): $INPUTFILE and $INPUTFILE2 differ:" >&2
+	echo "$HASH1"  >&2
+	echo "$HASH2"  >&2
+	exit 1
+fi
+
+#echo "$(basename $0) error: filetype unsupported ($INPUTFILETYPE): $INPUTFILE"  >&2
+#exit 1
diff --git a/bin/filetag b/bin/filetag
--- a/bin/filetag
+++ b/bin/filetag
@@ -1,1 +1,80 @@
-../../../bin/filetag
+#!/bin/sh
+
+if [ -z "$1" ] || [ "$#" -gt 2 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) INPUT_FILE"
+	echo "usage: $(basename $0) -TAG_NAME[=NEW_VALUE] INPUT_FILE"
+	echo
+	exit 0
+elif [ ! -f "$2" ] && [ ! -f "$1" ]; then
+	echo "$(basename $0) error: file does not exist: $1 $2" >&2
+	exit 1
+fi
+
+case $1 in
+	*=* ) # tag editing 
+		# just continue the script
+		;;
+	* )  # tag reading
+		exiftool "$@"  # MEMO: supports pdf files too!
+		_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		# some alternatives
+		if [ -f "$1" ]; then
+			# print all the tags, filename passed in $1
+			mediainfo "$1"
+			_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+			ffmpeg -i "$1"
+			_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		elif [ -f "$2" ]; then
+			# print a single tag, filename passed in $2
+			mediainfo -f "$2" | grep -i $1
+			_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+			ffmpeg -i "$2" 2>&1 | grep -i $1
+			_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		fi
+		# else 
+		exit 127
+		;;
+esac
+
+# detect the extension of the 1st passed file
+[ ! -f "$2" ] && exit 1
+INPUTFILE="$2"
+INPUTFILEEXT=$( echo -n "$INPUTFILE" | rev | cut -d'.' -f1 | rev )
+INPUTFILEEXT=$( echo -n $INPUTFILEEXT | tr '[A-Z]' '[a-z]' ) # force lowercase extension
+INPUTFILENAME="`basename \"$INPUTFILE\" | rev | cut -d'.' -f2- | rev`"
+# parse the new tag assignment
+FIELD="$( echo "$1" | cut -d- -f2 )"
+case $INPUTFILEEXT in
+	mp3 )
+		mid3v2 "$@"
+		[ $? -ne 127 ] && continue
+		mp3info "$@"
+		[ $? -ne 127 ] && continue
+		;&  # else fallthru
+	avi|mpeg|mpg|aac|wma|wmv|mp4 )
+		# ffmpeg alternative (not inplace)
+		ffmpeg -i "$INPUTFILE" -metadata "$FIELD" -codec copy "$TMPDIR/${INPUTFILENAME}_tagged.$INPUTFILEEXT"
+		mv "$TMPDIR/${INPUTFILENAME}_tagged.$INPUTFILEEXT" "$INPUTFILE"
+		exit $?
+		;;
+	mkv )
+		mkvpropedit --set "$FIELD" "$INPUTFILE"
+		exit $?
+		;;
+	ogg )
+		vorbiscomment --write --tag "$FIELD" "$INPUTFILE"  # --raw force utf8
+		exit $?
+		;;
+	flac )
+		metaflac --set-tag="$FIELD" "$INPUTFILE"
+		exit $?
+		;;
+	# TODO: more containers without write support in exiftool
+esac
+
+# else fallback to exiftool
+exiftool "$@"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+# else 
+exit 127
diff --git a/bin/fileunpack b/bin/fileunpack
--- a/bin/fileunpack
+++ b/bin/fileunpack
@@ -1,1 +1,249 @@
-../../../bin/fileunpack
+#!/bin/bash
+
+# perl script from atool package
+#command -p aunpack "$@"
+#_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+# see also:
+# https://github.com/xvoland/Extract/blob/master/extract.sh
+
+# else
+if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) FILE_TO_EXTRACT [OUTDIR]"
+	echo " if OUTDIR is omitted extract to the same path of FILE_TO_EXTRACT"
+	echo
+	exit 0
+fi
+
+[ -f "$1" ] && INPUTFILE="$1"
+[ -f "$2" ] && INPUTFILE="$2"
+
+if [ ! -f "$INPUTFILE" ]; then
+	echo "$(basename $0) error: file does not exist: $1" >&2
+	exit 1
+fi
+
+INPUTFILEFULLPATH="$(realpath $INPUTFILE)"
+INPUTFILEEXT=$( echo -n "$INPUTFILE" | rev | cut -d'.' -f1 | rev )
+INPUTFILEEXT=$( echo -n $INPUTFILEEXT | tr '[A-Z]' '[a-z]' ) # force lowercase extension
+INPUTFILENAME="`basename \"$INPUTFILE\" | rev | cut -d'.' -f2- | rev`"
+# fix for files with multiple extensions like "gbamidi-v1.0.tar.gz"
+INPUTFILEEXT2=$( echo -n "$INPUTFILENAME" | rev | cut -d'.' -f1 | rev )
+if [ "$INPUTFILEEXT2" = "tar" ]; then
+	# concatenate the extension
+	INPUTFILEEXT="$INPUTFILEEXT2.$INPUTFILEEXT"
+	# update the filename
+	INPUTFILENAME="`echo -n \"$INPUTFILENAME\" | rev | cut -d'.' -f2- | rev`"
+fi
+INPUTFILETYPE=$( file -b -i "$INPUTFILE" | cut -d';' -f1 )
+
+if [ ! -z "$2" ]; then
+	[ "$INPUTFILE" = "$1" ] && OUTPUTDIR="$2"
+	[ "$INPUTFILE" = "$2" ] && OUTPUTDIR="$1"
+else
+	OUTPUTDIR="$PWD/$INPUTFILENAME"
+fi
+
+[ ! -d "$OUTPUTDIR" ] && mkdir "$OUTPUTDIR"
+
+SCRIPT_START_TIMESTAMP=$(date +%s)
+NOTIFY_MIN_SECONDS=5
+# execute a function when the script exit
+function notify {
+	end=$(date +%s)
+	# notify only if some time is passed
+	if [ $(expr $end - $SCRIPT_START_TIMESTAMP) -gt $NOTIFY_MIN_SECONDS ]; then
+		exec notify "fileunpack finished"
+	fi
+}
+trap notify EXIT
+
+case "$INPUTFILEEXT" in
+	deb )
+		# try using dpkg-deb
+		dpkg-deb -x "$INPUTFILE" "$OUTPUTDIR"
+		_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		
+		# try using 7z + temp file
+		7z x -o"$TMPDIR"  "$INPUTFILE"
+		[ $? -eq 127 ] && exit 127
+		7z x -o"$OUTPUTDIR"  $TMPDIR/data.tar
+		rm $TMPDIR/data.tar
+		exit 0
+		;;
+	
+	rpm )
+		# try using rpm2cpio
+		cd $OUTPUTDIR
+		rpm2cpio "$INPUTFILEFULLPATH" | cpio -idvm
+		_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+		
+		# try using 7z + pipes
+		# 2IX: Reading archives from stdin is not implemented yet
+		#7z e "$INPUTFILE" -so | 7z e dummy -si -so | 7z e dummy -si
+
+		# try using 7z + temp file
+		7z x -o"$TMPDIR"  $INPUTFILE
+		[ $? -eq 127 ] && exit 127
+		7z x -o"$OUTPUTDIR"  "$TMPDIR/$INPUTFILENAME.cpio"
+		rm "$TMPDIR/$INPUTFILENAME.cpio"
+		exit 0
+		;;
+
+	gz )
+		gzip -dc < "$INPUTFILE" > "$OUTPUTDIR/$INPUTFILENAME"
+		exit $?
+		;;
+
+	tar )
+		tar -v -x -C "$OUTPUTDIR" -f "$INPUTFILE"
+		exit $?
+		;;
+	
+	tgz|tar.gz )
+		tar -v -x -z -C "$OUTPUTDIR" -f "$INPUTFILE"
+		exit $?
+		;;
+		
+	tbz|tar.bz2|tb2|tbz2 )
+		tar -v -x -j -C "$OUTPUTDIR" -f "$INPUTFILE"
+		exit $?
+		;;
+		
+	taz|tar.Z|tz )
+		tar -v -x -Z -C "$OUTPUTDIR" -f "$INPUTFILE"
+		exit $?
+		;;
+		
+	tlz|tar.lz|tar.lzma )
+		tar -v -x -a -C "$OUTPUTDIR" -f "$INPUTFILE"
+		exit $?
+		;;
+		
+	txz|tar.xz )
+		tar -v -x -J -C "$OUTPUTDIR" -f "$INPUTFILE"
+		exit $?
+		;;
+
+	cab )
+		cabextract -d"$OUTPUTDIR" "$INPUTFILE"
+		exit $?
+		;;
+		
+	zip|7z|arj|iso|cab )
+		7z x -bb1 -y -o"$OUTPUTDIR" "$INPUTFILE"
+		_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+		7za x -y -o"$OUTPUTDIR" "$INPUTFILE"
+		exit $?
+		;;
+	
+	rar )
+		rar x "$INPUTFILE" "$OUTPUTDIR"
+		exit $?
+		;;
+	
+	ace )
+		unace x -y "$INPUTFILE" "$OUTPUTDIR"
+		exit $?
+		;;
+	
+	msi|msp|doc|xls|ppt )
+		7z x -tCOMPOUND -y -o"$OUTPUTDIR"  "$INPUTFILE"
+		exit $?
+		;;
+	
+	swf )
+		swfextract -j 1 -p 1 -m 1 -M 1 -s 1 -F 1 -o "$OUTPUTDIR" "$INPUTFILE"
+		# WANTED: extract everything  https://github.com/matthiaskramm/swftools/issues/4
+		exit $?
+		;;
+		
+	bundle ) # source https://sskaje.me/2015/05/extract-vmware-bundle-file/
+		bash "$INPUTFILE" --extract "$OUTPUTDIR"
+		exit $?
+		;;
+	
+	srr )
+		srr -x "$INPUTFILE" -o"$OUTPUTDIR"
+		exit $?
+		;;
+	
+	exe ) # windows executable
+		# TODO: detect self-extracting archives
+		wrestool --verbose --extract --output="$OUTPUTDIR" "$INPUTFILE"
+		#exit $?
+		;;
+	
+	p7m )
+		# TODO: prevent creating subdir?
+		# extract the signed doc  https://en.quoll.it/faq/extracting-the-contents-of-a-digitally-signed-file-p7m/
+		openssl smime -verify -noverify -in "$INPUTFILE" -inform DER -out "$OUTPUTDIR/$INPUTFILENAME"
+		# extract the certificate  # TODO: detach user cert vs CA cert
+		openssl pkcs7 -inform DER -in "$INPUTFILE" -print_certs -out "$OUTPUTDIR/certs.pem"
+		# TODO: extract the detached signature in a p7s file
+		exit $?
+		;;
+esac
+
+case $INPUTFILETYPE in
+	application/pdf )
+		pdfimages -j "$INPUTFILE" "$OUTPUTDIR/"
+		pdftotext "$INPUTFILE" > "$OUTPUTDIR/$INPUTFILE.txt"
+		pdfdetach -saveall "$INPUTFILE" #-o "$OUTPUTDIR/"
+		exit $?
+		;;
+	
+	video/* )  # video files: extract individual tracks
+		#VIDEOEXT=$(ffmpeg -i "$INPUTFILE" 2>&1 | grep -io "video:....." | head -n 1 | cut -d ' ' -f2) # TODO: detect and extract all tracks, not just the 1st one
+		#ALTERNATIVE: VIDEOEXT=$(ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=nokey=1:noprint_wrappers=1 "$INPUTFILE")
+		VIDEOEXT=mkv  # force mkv container
+		ffmpeg -i "$INPUTFILE" -vcodec copy -an  "$OUTPUTDIR/${INPUTFILENAME}.$VIDEOEXT"
+		AUDIOEXT=$(ffmpeg -i "$INPUTFILE" 2>&1 | grep -io "audio:...." | head -n 1 | cut -d ' ' -f2) # TODO: detect and extract all tracks, not just the 1st one
+		ffmpeg -i "$INPUTFILE" -acodec copy -vn  "$OUTPUTDIR/${INPUTFILENAME}.$AUDIOEXT"
+		# alternatives:  mplayer -dumpvideo -dumpfile, mkvextract tracks , ...  http://softwarerecs.stackexchange.com/questions/34447/tool-to-dump-all-video-tracks-in-individual-files-with-automatic-file-extension
+		exit $?
+		;;
+	
+	#audio/* )# TODO: audio files -> extract album art and lyrics with exiftool
+	#	exiftool -a -picture -b "$INPUTFILE" -w "$OUTPUTFILE"
+	#	exiftool -a -lyric -b "$INPUTFILE" -w "$OUTPUTFILE"
+	
+	# TODO: image files -> extract embedded preview
+	#  exiftool -b -PreviewImage -w "$OUTPUTFILE" "$INPUTFILE"
+
+esac
+
+#else try with some generic unpackers
+
+# try game archives via GameExtractor  http://www.watto.org/game_extractor.html
+gameextractor -extract -input "$(readlink -f "$INPUTFILE")" -output "$OUTPUTDIR"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+# try some generic unpackers
+binwalk --extract --carve "$INPUTFILE"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+#retdec-unpacker "$INPUTFILE"
+
+foremost -v -o "$OUTPUTDIR" -i "$INPUTFILE"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+7z x -bb1 -y -o"$OUTPUTDIR" "$INPUTFILE"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+7za x -y -o"$OUTPUTDIR" "$INPUTFILE"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+rar x "$INPUTFILE" "$OUTPUTDIR"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+if [ "$INPUTFILEEXT" = "zip" ]; then
+	unzip "$INPUTFILE" -d "$OUTPUTDIR"
+	_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+fi
+
+# TODO? shar
+# TODO? .lz -> lzip
+
+exit 127
diff --git a/bin/finddb b/bin/finddb
--- a/bin/finddb
+++ b/bin/finddb
@@ -1,1 +1,39 @@
-../../../bin/finddb
+
+_QUERY="$1"
+_SEARCHDIR="$2"
+
+if [ ! -d "$_SEARCHDIR" ]; then
+	echo "$(basename $0) error: dir not found: $_SEARCHDIR" >&2
+	exit 1
+fi
+
+#echo "$(basename $0): searching in $_SEARCHDIR for $_QUERY ..." >&2
+
+# convert wildcards to regexpr
+#_QUERY=$( echo "$_QUERY" | tr '*' '\.*' | tr '\.' '\\\.'  | tr '?' '\.' )
+_QUERY=$( echo "$_QUERY" | sed 's/\./\\\./g; s/\*/\.\*/g; s/?/./g' )
+
+ugrep -i -I -r -z -w --exclude-dir=_\* --exclude=\*.{html,htm,xml,json} -H  "$_QUERY" "$_SEARCHDIR/" | cut -c 1-260  # TODO: exclude more files
+[ $? -eq 127 ] && grep -i -I -r --exclude-dir=_\* -H  "$_QUERY" "$_SEARCHDIR/"
+[ $? -eq 1 ] && echo "$(basename $0): nothing found" >&2
+exit $?
+
+
+# OLD:
+# also search in zipped files:
+#if [ "$3" = "-z" ]; then
+#OLD: zzfind "$_SEARCHDIR/*.zip" "$_QUERY" -dir!_*  #| grep -v '.htm\|wikipedia' #| less -S
+#NO(BUGGY)? zipgrep "$_QUERY" "$_SEARCHDIR/*.zip" 2>& 1  | grep -v 'filename not matched'
+#TODO: rg --search-zip ...  # https://github.com/BurntSushi/ripgrep/issues/1479
+
+
+
+# ALTERNATIVE:
+PAGER="less -S"
+IGNOREFILTER="grep -v -e '.htm' -e 'wikipedia'"
+# search in plaintext files
+#find "$_SEARCHDIR/" -not -name "*.csv" -not -name "*.tsv" -not -name "*.zip" -not -name "*.rar" -not -name "*.gz" -not -name "*.7z" -type f -print0 | xargs -0 -n 1 -r  grep -i -H -F "$1" | $IGNOREFILTER | $PAGER
+# search in csv files and pretty print the results
+#find "$_SEARCHDIR/" \( -iname "*.csv" -o -iname "*.tsv" \) -print0 | xargs -0 -n 1 -r  csv grep "$1"
+# search in compressed files
+find "$_SEARCHDIR/" \( -iname "*.zip" -o -iname "*.rar" -o -iname "*.7z" -o -iname "*.gz" \) -print0 | xargs -0 -n 1 -r  filegrep "$1" | less -S
diff --git a/bin/geocode b/bin/geocode
--- a/bin/geocode
+++ b/bin/geocode
@@ -1,1 +1,182 @@
-../../../bin/geocode
+#!/bin/bash
+
+command -p geocode "$@"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+# else bash alternative
+[ -z "$1" ] && while read -r line ; do $0 "$line" ; done && exit $?
+[ -f "$1" ] && while read -r line ; do $0 "$line" ; done < "$1"  && exit $?
+
+# args checking
+if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
+	echo "usage: $(basename $0) [-m reverse] [--distance] QUERY"
+	echo
+	echo "examples: geocode \"Ottawa, ON\", geocode LAT,LON, geocode --distance Milano Roma"
+	exit 0
+fi
+
+if [ "$1" = "-m" ] && [ "$2" = "reverse" ]; then
+	# geodecode
+	
+	if [ -z "$3" ] ; then
+		echo "usage: $(basename $0) -m reverse LAT,LON"
+		echo
+		exit 1
+	fi
+	# else
+	
+	LATLNG="$3"
+	LAT=$( echo "$LATLNG" | cut -d" " -f1 )
+	LONG=$( echo "$LATLNG" | cut -d" " -f2 )
+
+	# using python-geopy  https://github.com/geopy/geopy
+	python3 -c "from geopy.geocoders import Nominatim; p = Nominatim().reverse(\"$LATLNG\"); from pprint import pprint ; pprint(p.raw)" >&2   # TODO: colorize with IPython.utils.PyColorize?
+	echo
+	python3 -c "from geopy.geocoders import Nominatim; p = Nominatim().reverse(\"$LATLNG\"); print(str(p) + \" = \" + str(p.address) )"
+	[ $? -eq 0 ] && exit 0
+
+	# using node-geocoder-cli  https://www.npmjs.com/package/node-geocoder
+	geocoder reverse $LAT $LONG
+	[ $? -eq 0 ] && exit 0
+
+	# else alternative using remote web APIs
+
+	# TODO: check float args
+	echo "$LAT" | grep -qE '^\-?[0-9]?\.?[0-9]+'
+	[ $? -ne 0 ] && LAT=""
+	echo "$LONG" | grep -qE '^\-?[0-9]?\.?[0-9]+'
+	[ $? -ne 0 ] && LONG=""
+	if [ -z "$LAT" ] || [ -z "$LONG" ]; then
+		echo "$(basename $0) err: invalid coords specified"  >&2
+		exit 1
+	fi
+
+	# try with OSM Nominatim  https://wiki.openstreetmap.org/wiki/Nominatim
+	ZOOM=18
+	wget -q -U Firefox -O- "https://nominatim.openstreetmap.org/reverse?format=json&lat=$LAT&lon=$LONG&zoom=$ZOOM&addressdetails=1"
+	#[ $? -eq 0 ] && exit 0
+
+	# try with Photon OpenStreetMap public server
+	wget -q -U Firefox -O- "http://photon.komoot.de/reverse?lon=$LONG&lat=$LAT"
+	#[ $? -eq 0 ] && exit 0
+
+	# try with Google API
+	# TODO: detect "OVER_QUERY_LIMIT" in output
+	wget -q -U Firefox -O- "https://maps.googleapis.com/maps/api/geocode/json?latlng=$LAT,$LONG&sensor=false"
+	#[ $? -eq 0 ] && exit 0
+
+	#DISCONTINUED: try with yahoo apis
+	#"http://query.yahooapis.com/v1/public/yql?q=SELECT%20*%20FROM%20geo.placefinder%20WHERE%20text%3D%22{$LAT}%2C{$LONG}%22%20and%20gflags%3D%22R%22"
+
+	exit $?
+
+elif [ "$1" = "--distance" ]; then
+	# distance between 2 points
+	shift
+	
+	if [ -z "$3" ] ; then
+		echo "usage: $(basename $0) --distance LAT1 LON1 LAT2 LON2"
+		echo "usage: $(basename $0) --distance location_name1 location_name2"
+		echo
+		exit 1
+	fi
+	# else
+	
+	SRCQUERY="$2"
+	DSTQUERY="$3"
+	#LAT=$( echo "$LATLNG" | cut -d" " -f1 )
+	#LONG=$( echo "$LATLNG" | cut -d" " -f2 )
+	lat_1="$1"
+	lon_1="$2"
+	lat_2="$3"
+	lon_2="$4"
+	
+	# TODO: using qacl  https://github.com/Qalculate/libqalculate/issues/254
+	
+	# TODO: using python-geopy  https://github.com/geopy/geopy
+	echo 'python-geopy:'
+	python -c "from geopy.distance import geodesic; print(geodesic(($lat_1, $lon1), ($lat_2, $lon2)))"
+	#[ $? -eq 0 ] && exit 0
+	
+	# TODO: alternative using sklearn.metrics.pairwise.haversine_distances  https://stackoverflow.com/questions/29545704/fast-haversine-approximation-python-pandas#answer-41858332
+	
+	# TODO: OSM alternative  https://help.openstreetmap.org/questions/37861/distance-matrix-api
+	
+	# using Google Distance Matrix API  https://developers.google.com/maps/documentation/distance-matrix/start
+	wget -q -U Firefox -O- "https://maps.googleapis.com/maps/api/distancematrix/json?units=metric&origins=$( urlencode -m "$SRCQUERY" )&destinations=$( urlencode -m "$DSTQUERY" )&key=GOOGLE_API_KEY"
+	#[ $? -eq 0 ] && exit 0
+	
+	echo
+
+	# else pure bash alternative
+	# source: https://ethertubes.com/bash-snippet-calculating-the-distance-between-2-coordinates/
+	# TODO: convert in a pure bc script
+	deg2rad () { bc -l <<< "$1 * 0.0174532925" ; }
+	rad2deg () { bc -l <<< "$1 * 57.2957795" ; }
+	acos () { pi="3.141592653589793" ; bc -l <<< "$pi / 2 - a($1 / sqrt(1 - $1 * $1))"; }
+	delta_lat=`bc <<<"$lat_2 - $lat_1"`
+	delta_lon=`bc <<<"$lon_2 - $lon_1"`
+	lat_1="`deg2rad $lat_1`"
+	lon_1="`deg2rad $lon_1`"
+	lat_2="`deg2rad $lat_2`"
+	lon_2="`deg2rad $lon_2`"
+	delta_lat="`deg2rad $delta_lat`"
+	delta_lon="`deg2rad $delta_lon`"
+	distance=`bc -l <<< "s($lat_1) * s($lat_2) + c($lat_1) * c($lat_2) * c($delta_lon)"`
+	distance=`acos $distance`
+	distance="`rad2deg $distance`"
+	#miles:
+	#distance=`bc -l <<< "$distance * 60 * 1.15078"`
+	# km:
+	distance=`bc -l <<< "$distance * 60 * 1.15078 * 1.609344"`
+	distance=`bc <<< "scale=4; $distance / 1"`
+	echo "$distance km"
+	exit $?
+
+else
+	# geoencode
+	QUERY="$@"
+	
+	# using python-geopy  https://github.com/geopy/geopy
+	python3 -c "from geopy.geocoders import Nominatim; p = Nominatim().geocode(\"$QUERY\"); from pprint import pprint ; pprint(p.raw)" >&2  # TODO: colorize with IPython.utils.PyColorize?
+	echo
+	python3 -c "from geopy.geocoders import Nominatim; p = Nominatim().geocode(\"$QUERY\"); print(str(p) + \" = \" + str(p.point) + \" = lon : \" + str(p.longitude) + \" , lat : \" + str(p.latitude) )"
+	[ $? -eq 0 ] && exit 0
+	
+	# using node-geocoder-cli  https://www.npmjs.com/package/node-geocoder
+	geocoder geocode "$QUERY"
+	[ $? -eq 0 ] && exit 0
+	
+	# else alternative using remote web APIs
+
+	# try with OSM Nominatim  https://wiki.openstreetmap.org/wiki/Nominatim
+	wget -q -U Firefox -O- "https://nominatim.openstreetmap.org/search?q=$( urlencode "$QUERY" )&format=json&limit=1&addressdetails=1" | jq .
+	[ $? -eq 0 ] && exit 0
+
+	# try with Photon OpenStreetMap public server
+	wget -q -U Firefox -O- "http://photon.komoot.de/api?q=$( urlencode "$QUERY" )" | jq .
+	[ $? -eq 0 ] && exit 0
+
+	# try with Yahoo API
+	# OLD URL="https://query.yahooapis.com/v1/public/yql?q=select centroid from geo.places where text=\"$1\"&format=json"
+	wget -q -U Firefox -O- "https://query.yahooapis.com/v1/public/yql?q=select * from geo.places where text=\"$QUERY\"&format=json"
+	[ $? -eq 0 ] && exit 0
+
+	# try with Google Maps Geocoding API  https://developers.google.com/maps/documentation/geocoding/intro
+	wget -q -U Firefox -O- "https://maps.googleapis.com/maps/api/geocode/json?language=it&address=$( urlencode "$QUERY" )"
+	exit $?
+fi
+
+# else
+exit 127
+
+
+# OLD ALTERNATIVE using xplanet
+#xplanet -pango -output "$TMPDIR/$$.png" -num_times 1 -geometry 640x480 -searchdir $PENDRIVE/Documents/img/space/maps/ -body earth -latitude $1 -longitude $2 -radius 1800 
+# WANTED: disable sun simulation:  NO? -date 19900617.120000
+# [-projection orthographic]
+# TODO: convert "$TMPDIR/$$.png" ... (add a marker @ coord 320:240) "$TMPDIR/$$-final.png"
+#cp "$TMPDIR/$$.png" "$TMPDIR/$$-final.png"
+#xdg-open "$TMPDIR/$$-final.png"
+#rm -f "$TMPDIR/$$.png"
+#rm -f "$TMPDIR/$$-final.png"
diff --git a/bin/getip b/bin/getip
--- a/bin/getip
+++ b/bin/getip
@@ -1,1 +1,67 @@
-../../../bin/getip
+#!/bin/sh
+
+if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) [HOSTNAME]"
+	exit 0
+fi
+
+if [ "$1" = "" ]; then
+    #[ ! -z "$ANDROID_ROOT" ] && IFACE=eth0 # Android always defaults to eth0?
+    [ -z "$IFACE" ] && IFACE=$(route | grep '^default' | grep -o '[^ ]*$' | head -n1)
+    
+    #echo "$(basename $0): private IPs:"
+    #ifconfig $IFACE | grep "inet addr"
+    #ifconfig | grep -E "Link encap|inet addr"
+    PRIVATEIP=$( ip -f inet -o addr show $IFACE |cut -d\  -f 7 | cut -d/ -f 1 )
+    #PRIVATEIP=$( ip -f inet -o addr show $IFACE | egrep -o '([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}' | head -n 1 )
+    [ -z "$PRIVATEIP" ] && PRIVATEIP=$( ifconfig $IFACE | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}' )  # old method
+    [ -z "$PRIVATEIP" ] && exit 1
+    echo "$PRIVATEIP"
+    
+    # also checks the public IP
+    #echo "$(basename $0): public IP:"
+    PUBLICIP=$(wget -q -O- -T2 http://checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//')
+    [ -z "$PUBLICIP" ] && PUBLICIP=$(wget -q -O- -T2 http://api.ipify.org/)
+    [ -z "$PUBLICIP" ] && PUBLICIP=$(wget -q -O- -T2 http://ipinfo.io/ip)
+    [ -z "$PUBLICIP" ] && PUBLICIP=$(wget -q -O- -T2 http://whatismijnip.nl | cut -d" " -f5)
+    [ -z "$PUBLICIP" ] && PUBLICIP=$(wget -q -O- -T2 http://httpbin.org/ip | grep -Eo '"origin":.*?[^\\]"' | cut -d\" -f4)
+    [ -z "$PUBLICIP" ] && PUBLICIP=$(wget -q -O- -T2 http://ip-api.com/json | grep -Eo '"query":.*?[^\\]"' | cut -d\" -f4)
+    [ -z "$PUBLICIP" ] && PUBLICIP=$(curl http://ifconfig.me/ip)
+    #SLOW, NEED CUSTOM UA [ -z "$PUBLICIP" ] && PUBLICIP=$(wget -q -O- -T2 -U "Firefox 4.0b10. Mozilla/5.0 (X11; Linux i686; rv:2.0b10) Gecko/20100101 " http://ifconfig.me/ip)
+    if [ -z "$PUBLICIP" ]; then
+        echo "$(basename $0) warn: no public IP found (are you connected?)" >&2
+    elif [ "$PUBLICIP" != "$PRIVATEIP" ]; then
+        echo "$(basename $0) warn: private IP mismatches the public IP (NATted connection?): $PUBLICIP" >&2
+    fi
+    exit 0
+fi
+# else try other methods
+
+# remote lookup with nslookup
+REMOTEIP=$(nslookup $1   | tail -n3 | grep 'Address') # default DNS server
+[ -z "$REMOTEIP" ] && REMOTEIP=$(nslookup $1 8.8.8.8  | tail -n3 | grep 'Address')  # Google DNS
+[ -z "$REMOTEIP" ] && REMOTEIP=$(nslookup $1 208.67.222.222  | tail -n3 | grep 'Address')  # OpenDNS
+[ -z "$REMOTEIP" ] && REMOTEIP=$(nslookup $1 84.200.69.80  | tail -n3 | grep 'Address')  # DNS.WATCH
+[ -z "$REMOTEIP" ] && REMOTEIP=$(nslookup $1 91.239.100.100  | tail -n3 | grep 'Address')  # UncensoredDNS
+# TODO: more uncensored DNS? https://www.c0urier.net/2013/uncensored-and-fast-dns-servers
+if [ ! -z "$REMOTEIP" ]; then
+	echo "$REMOTEIP" | cut -d':' -f2 | tr -d '[:space:]'
+	exit 0
+fi
+# else continue
+
+# zeroconf names
+avahi-resolve --name $1  2> /dev/null
+[ $? -eq 0 ] && exit 0  # TODO: fix exit status on failure
+
+# netbios names
+nmblookup $1 | cut -d' ' -f1 | grep "\."
+[ $? -eq 0 ] && exit 0  # TODO: fix exit status on failure
+
+# lookup via systemd
+systemd-resolve $1 | head -n1 | cut -d' ' -f2 | cut -d'%' -f1
+[ $? -eq 0 ] && exit 0  # TODO: fix exit status on failure
+
+#else
+echo "$(basename $0) err: unable to resolve: $1"  >&2
+exit 1
diff --git a/bin/hexalter b/bin/hexalter
--- a/bin/hexalter
+++ b/bin/hexalter
@@ -1,1 +1,58 @@
-../../../bin/hexalter
+#!/bin/sh
+
+# clone of http://www.kuwanger.net/hexalter.zip
+# with added view mode
+
+command -p hexalter "$@"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "syntax: $(basename $0) FILE ADDRESS[=NEW VALUE]"
+	echo ""
+	exit 0
+elif [ ! -f "$1" ]; then
+	echo "$(basename $0) error: file does not exist: $1" >&2
+	exit 1
+elif [ -z "$2" ]; then
+	echo "$(basename $0) error: no address specified" >&2
+	exit 1
+fi
+
+INPUTFILE="$1"
+
+shift
+
+# iterate over args
+for ARG in "$@"
+do
+	case "$ARG" in
+		*=* )
+			# edit mode
+			BASEADDR=$( echo -n $ARG | cut -d= -f1 )
+			BASEADDRDEC=$( printf "%d" $BASEADDR )
+			# iterate over comma-separated list
+			for VALUE in $( echo -n $ARG | cut -d= -f2 | sed "s/,/ /g"  )
+			do
+				VALUEHEX=$( printf "%v" $VALUE )
+				echo "$(basename $0) warn: patching $VALUEHEX in $BASEADDRDEC" >&2
+				printf "\x0$VALUEHEX" | dd of="$INPUTFILE" bs=1 seek=$BASEADDRDEC conv=notrunc
+				#ALTERNATIVE: echo -ne "\x$VALUEHEX" | dd ..
+				#MORE ALTERNATIVEs: ucon64 --nbak --poke="$1" "$2";
+				BASEADDRDEC=$( expr $BASEADDRDEC + 1 ) # increase baseaddr
+			done
+			#echo "Patching successful"
+			exit 0
+			;;
+	esac
+	
+	# else read mode
+	hexdump "$INPUTFILE" -s $ARG -n 1 -e '1/1 "%.2X\n"'
+
+	# check invalid address
+	#if [ "$(printf "%d" $ADDR)" -gt "$(stat -c%s "$1")" ]; then
+	#	echo "$(basename $0) error: invalid address specified: $ADDR (max allowed is $(printf "%X\n" $(stat -c%s "$1")))" >&2
+	#	continue
+	#fi
+
+done
+
diff --git a/bin/ldd b/bin/ldd
--- a/bin/ldd
+++ b/bin/ldd
@@ -1,1 +1,18 @@
-../../../bin/ldd
+
+/usr/bin/ldd "$@"
+#command -p ldd "$@"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+# else alternative using readelf/strings
+if [ "$#" -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) FILE"
+	echo
+	exit 0
+elif [ ! -f "$1" ]; then
+	echo "$(basename $0) error: file does not exist: $1" >&2
+	exit 1
+fi
+
+readelf -d "$1" | grep -F ".so"
+
+strings "$1" | grep -F ".so"
diff --git a/bin/lrctransliterate b/bin/lrctransliterate
--- a/bin/lrctransliterate
+++ b/bin/lrctransliterate
@@ -1,1 +1,32 @@
-../../../bin/lrctransliterate
+#!/bin/sh
+
+# add transliteration next to every lrc line
+
+# force unicode
+export LC_ALL=C.UTF-8
+
+[ -z "$1" ] && exit
+#[ ! -z ] OUTFILE="$2"
+
+echo "[by:eadmaster (automatic transliteration, may contain errors)]\r"
+
+
+while read LINE          
+do
+	LINE="$( echo -n "$LINE" | sed -e 's/$/\r/' )"   # force windows newlines
+	# skip lines ending with "]"
+	#echo -n "$LINE" | grep -q '\]$'
+	#[ $? -eq 0 ] && continue
+	# remove the parentesis
+	LINE="$( echo -n "$LINE" | sed 's/([^)]*)//g' )"
+
+	TIMETAG="$( echo -n "$LINE" | rev | cut -d] -f2- | rev )"
+	LRCLINE="$( echo -n "$LINE" | rev | cut -d] -f1 | rev )"
+	TRANSLINE="$( jap2romaji "$LRCLINE" )"
+	#TRANSLINE="$( echo -n "$LRCLINE" | jakaroma 2> /dev/null | kanji2kana | kana2romaji | uconv -x 'Any-Latin;Latin-ASCII' | tr -d '\n' )"
+	if [ -z "$TIMETAG" ]; then
+		echo ""
+	else
+		echo "${TIMETAG}]$TRANSLINE"  #>> $OUTFILE
+	fi
+done  <"$1"
diff --git a/bin/mediahash b/bin/mediahash
--- a/bin/mediahash
+++ b/bin/mediahash
@@ -1,1 +1,40 @@
-../../../bin/mediahash
+#!/bin/sh
+
+# args checking
+if [ "$#" -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) MEDIA_FILE"
+	echo
+	exit 0
+elif [ ! -f "$1" ]; then
+	echo "$(basename $0) error: file does not exist: $1" >&2
+	exit 1
+fi
+
+INPUTFILE="$1"
+INPUTFILEEXT=$( echo -n "$INPUTFILE" | rev | cut -d'.' -f1 | rev )
+INPUTFILEEXT=$( echo -n $INPUTFILEEXT | tr '[A-Z]' '[a-z]' ) # force lowercase extension
+INPUTFILETYPE=$( file -b -i "$INPUTFILE" | cut -d';' -f1 )
+
+ffmpeg -loglevel error -i "$INPUTFILE" -f crc - 2>/dev/null  # faster
+
+ffmpeg -loglevel error -i "$INPUTFILE" -f md5 - 2>/dev/null
+
+ffmpeg -loglevel error -i "$INPUTFILE" -f hash - 2>/dev/null  # default to SHA256 (slowest)?
+
+case $INPUTFILETYPE in
+	image/*|audio/* )
+		#TODO: alternative using vlc
+		#vlc -I rc "$INPUTFILE" :sout='#std{mux=raw,access=file,dst=-}' vlc://quit | md5sum
+		
+		# TODO: audio fingerprinting
+		
+		exit $?
+		;;
+	
+	video/* )
+		# TODO: video fingerprinting
+		
+		exit $?
+		;;
+		
+esac
diff --git a/bin/opcodefind b/bin/opcodefind
--- a/bin/opcodefind
+++ b/bin/opcodefind
@@ -1,1 +1,96 @@
-../../../bin/opcodefind
+#!/bin/sh
+
+OPCODES_CSV_PATH=$PENDRIVE/Documents/db/opcode
+
+# args checking
+if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) [opcode] [arch]"
+	echo
+	echo "-L list all supported archs"
+	#echo "if arch is omitted defaults to x86"
+	echo "if opcode is omitted will list all the opcodes"
+	exit 0
+fi
+
+OPCODE=$1
+OPCODE=$( echo -n $OPCODE | tr '[A-Z]' '[a-z]' )   # force lowercase
+
+if [ ! -z "$2" ] ; then
+	ARCH=$2
+	ARCH=$( echo -n $ARCH | tr '[A-Z]' '[a-z]' )  # force lowercase
+	# check arch aliases
+	case "$ARCH" in
+		atmel ) ARCH=avr ;;
+		sms|zx|msx ) ARCH=z80 ;;  # gb have specific arch
+		c64|nes|pce|atari ) ARCH=6502 ;;  # snes have specific arch
+		68k|mac|amiga|smd ) ARCH=m68k ;;
+		psx|ps1|ps2|n64 ) ARCH=mips ;;
+		32x|ss|sat|dc ) ARCH=sh ;;  # SuperH-4
+		#TODO: nds|psp|3ds ) ARCH=arm.as ; export RZ_ARM32_AS=/opt/devkitpro/devkitARM/bin/arm-none-eabi-as ;;
+		#TODO: nsw|switch ) ARCH=arm.as ; export RZ_ARM64_AS=devkita64 ;;
+		#TODO: ngc|wii|wiiu ) ARCH=ppc.as ; export RZ_PPC_AS=/opt/devkitpro/devkitPPC/bin/powerpc-eabi-as ;; # TODO use rz-ghidra for these https://github.com/rizinorg/rz-ghidra + https://github.com/Maschell/GhidraRPXLoader
+		#TODO: imac|360|ps3 ) ARCH=ppc.as ; RZ_PPC_AS=??? ;; # TODO use rz-ghidra for these https://github.com/rizinorg/rz-ghidra + https://github.com/Maschell/GhidraRPXLoader
+		#TODO: amd64|x86_64 ) ARCH=x86 ; ARCH_BITS=64 ;;
+	esac
+
+	#if [ -z "$ARCH" ]; then
+	#	ARCH=x86  # defaults to x86	
+	#fi
+
+fi
+if [ -z "$ARCH" ] || [ "$1" = "-L" ] ; then	
+	# echo "$0: err: missing or invalid arch." >&2
+	rz-asm -L
+	exit 1
+fi
+
+TARGET_DB_FILE=$(find "$OPCODES_CSV_PATH" -iname *$ARCH*)
+if [ -z "$TARGET_DB_FILE" ]; then
+	echo "$0 err: no db file found matching $ARCH" >&2
+	exit 1
+fi
+
+
+echo "$0: querying $TARGET_DB_FILE" >&2
+
+# TODO: fixed column width, pretty print with colors?
+head -n1 $TARGET_DB_FILE | column -s, -t
+grep -i $OPCODE  $TARGET_DB_FILE  | column -s, -t
+
+exit $?
+
+
+
+# OLD: using rizin
+
+export RZ_ARCH=$ARCH
+export RZ_BITS=$ARCH_BITS
+
+echo "$0: using arch $ARCH..." >&2
+
+OPCODE=$2
+OPCODE=$( echo -n $OPCODE | tr '[A-Z]' '[a-z]' )   # force lowercase
+
+#TODO: check opcode aliases
+
+if [ -z "$OPCODE" ]; then
+	[ -f /usr/share/radare2/2.3.0/opcodes/$ARCH.sdb ] && RADARE_OPCODES_PATH=/usr/share/radare2/2.3.0/opcodes/$ARCH.sdb
+	[ -f /usr/share/rizin/0.2.1/opcodes/$ARCH.sdb ] && RADARE_OPCODES_PATH=/usr/share/rizin/0.2.1/opcodes/$ARCH.sdb
+	[ -f "$RADARE_OPCODES_PATH" ] && strings $RADARE_OPCODES_PATH | less
+	# TODO: replace with proper rizin command  https://github.com/rizinorg/rizin/issues/1100
+	#rizin -q -c"aoja;q"
+	exit $?
+fi
+
+# TODO: if $OPCODE is an int pass the "-d" switch
+
+rz-asm -w -a $ARCH $OPCODE
+
+# TODO: = replaced with  - in   https://github.com/rizinorg/rizin/issues/1100
+#rasm2 -B -q -a $ARCH $OPCODE | radare2 -q -a $ARCH -c"aod $OPCODE;q" =
+
+#rz-asm -B -q -a $ARCH $OPCODE | rizin -q -a $ARCH -c"ao $OPCODE;q" = #| grep -v address   # TODO: remove more fields: esilcost, disasm
+exit $?
+
+# ALTERNATIVES:
+#  NO? capstone (few archs supported) https://www.capstone-engine.org/lang_python.html
diff --git a/bin/patchcht b/bin/patchcht
--- a/bin/patchcht
+++ b/bin/patchcht
@@ -1,1 +1,116 @@
-../../../bin/patchcht
+
+
+# args checking
+if [ "$#" -ne 2 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ ! -f "$1" ] || [ ! -f "$2" ] ; then
+	echo "usage: $(basename $0) ORIGINAL_ROM_FILE INPUT_CHT_FILE"
+	echo "generate a patched ROM with the same name of INPUT_CHT_FILE"
+#	echo "MEMO:  INPUT_CHT_FILE must have unix line endings"
+#	echo "MEMO:  RAW codes usually require an un-headered ROM dump"
+	echo
+	exit 0
+fi
+
+INPUTROMFILE="$1"
+INPUTROMFILEEXT=$( echo -n "$INPUTROMFILE" | rev | cut -d'.' -f1 | rev )
+INPUTROMFILEEXT=$( echo -n $INPUTROMFILEEXT | tr '[A-Z]' '[a-z]' ) # force lowercase extension
+INPUTCHTFILE="$2"
+INPUTCHTFILENAME="`echo -n \"$INPUTCHTFILE\" | rev | cut -d'.' -f2- | rev`"
+OUTPUTROMFILE="$INPUTCHTFILENAME.$INPUTROMFILEEXT"
+
+# try auto autodetect system using $INPUTROMFILEEXT
+case $INPUTROMFILEEXT in
+	nes ) ROM_SYSTEM=nes ; echo "$(basename $0) warn: NES GG patching requires ucon64 >= 2.0.2 to work properly" >&2 ;;
+	smc|sfc ) ROM_SYSTEM=snes ;;
+	sms|gg ) ROM_SYSTEM=sms ;;
+	gen|bin ) ROM_SYSTEM=gen ; echo "$(basename $0) warn: Genesis GG patching requires ucon64 >= 2.0.2 to work properly" >&2 ;;
+	smd ) echo "$(basename $0): error: ucon64 cannot patch Genesis ROMs in SMD format, convert them to Magicom/BIN/RAW format" >&2 ;;
+	gb|gbc|gba ) ROM_SYSTEM=gb ;;
+	pce ) ROM_SYSTEM=pce ;;
+	#z64|n64 ) ROM_SYSTEM=n64 ;;
+#--swan
+# --jag
+# --ngp
+# --vboy 
+# ...  http://ucon64.sourceforge.net/ucon64/readme.html
+esac
+
+if [ -z "$ROM_SYSTEM" ]; then
+	echo "$(basename $0) error: ROM dump format not supported: $INPUTFILEEXT" >&2
+	exit 1
+elif [ ! "$INPUTROMFILE" = "$OUTPUTROMFILE" ]; then
+	cp "$INPUTROMFILE" "$OUTPUTROMFILE"
+	[ $? -ne 0 ] && exit 1
+else
+#	echo "$(basename $0) error: conflicting filename (output would overwrite the input): $INPUTCHTFILE" >&2
+#	exit 1
+	cp "$INPUTROMFILE" "$INPUTROMFILE.bak"
+	[ $? -ne 0 ] && exit 1
+	echo "$(basename $0) warn: input and output filename are the same, a backup was made" >&2
+fi
+
+# remove ROM header if necessary
+#ucon64 "$OUTPUTROMFILE" | grep 'Backup unit/emulator header: Yes'
+#if [ $? -eq 0 ] ; then
+#	ucon64 --nbak --stp "$OUTPUTROMFILE"
+#	HEADER_REMOVED=true
+#fi
+
+# fix wrong newlines in the cht file
+#dos2unix "$INPUTCHTFILE"
+
+while read line          
+do
+	# skip empty lines
+	#[ ${#line} = 0 ] && continue 
+	[ -z "$line" ] && continue
+	# [ "$line" = "" ] && continue
+	
+	echo "$line" | grep -F '+'
+	if [ $? -eq 0 ]; then
+		echo "$(basename $0) warn: combined codes on the same line are not supported (line skipped): $line"  >&2
+		continue
+	fi
+	
+	# determine if current line is a cheat using grep (more reliable)
+	echo "$line" | grep -qE '^[0-9A-Z]{3,}-[0-9A-Z]{3,}|^[A-Z]{6,}'  # matches strings like "XXX-XXX" or "XXXXXX" (Game Genie codes)
+	if [ $? -eq 0 ]; then
+		# patch gamegenie code type
+		current_code=$line
+		echo "$(basename $0): patching code: $line"
+		ucon64 --nbak --$ROM_SYSTEM --gg=$current_code "$OUTPUTROMFILE"  > /dev/null
+		#[ $? -ne 0 ] && echo "$(basename $0) warn: code patching failed" >&2
+		continue
+	fi
+	
+	echo "$line" | grep -qE '^[0-9A-F]{3,}:[0-9A-F]{2,}'  # matches hex strings like "AAAA:VV" (RAW codes)
+	if [ $? -eq 0 ]; then
+		# patch RAW code types
+		current_code=$line
+		echo "$(basename $0): patching code: $line"
+		ucon64 --nbak --poke=$current_code "$OUTPUTROMFILE"  > /dev/null
+		#[ $? -ne 0 ] && echo "$(basename $0) warn: code patching failed" >&2
+		continue
+	fi
+	
+#endwhile
+done <"$INPUTCHTFILE"
+
+# restore the header
+#[ "$HEADER_REMOVED" = "true" ] && ucon64 --nbak --$ROM_SYSTEM --ins "$OUTPUTROMFILE"
+
+# fix the header checksum
+if [ "$INPUTROMFILEEXT" != "nes" ]; then
+	ucon64 --nbak --$ROM_SYSTEM --chk "$OUTPUTROMFILE"   > /dev/null
+	[ $? -ne 0 ] && echo "$(basename $0) warn: could not fix the header checksum" >&2
+fi
+
+# generate an ips patch
+ucon64 --mki="$INPUTROMFILE" "$OUTPUTROMFILE"   > /dev/null
+[ $? -ne 0 ] && echo "$(basename $0) warn: ips creation failed" >&2
+
+#rm "$OUTPUTROMFILE"
+#mv "$INPUTCHTFILENAME.ips" "$INPUTCHTFILENAME"
+
+#mv "$INPUTCHTFILENAME.ips" "../$INPUTROMFILE.ips"
+#cp "$INPUTCHTFILE" "../$INPUTROMFILE.ips.txt"
+#7z a "$PWD.7z" *.*
diff --git a/bin/penv b/bin/penv
--- a/bin/penv
+++ b/bin/penv
@@ -1,1 +1,45 @@
-../../../bin/penv
+#!/bin/sh
+
+# args checking
+if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) [-s FOO=bar] PPID|PATTERN"
+	echo " with the -s switch alter the environment"
+	exit 0
+elif [ "$1" = "-s" ] && [ "$#" -ne 3 ] ; then
+	echo "$(basename $0) error: invalid syntax" >&2
+	exit 1
+elif [ "$1" = "-s" ] && [ "$#" -eq 3 ] ; then
+	PATTERN=$3
+else
+	PATTERN=$1
+fi
+
+#pid=$(ps ax | grep $PATTERN | grep -v grep | cut -f2 -d " ")
+# safer alternative using pgrep (in busybox)
+if [ -d "/proc/$PATTERN" ]; then
+	pid=$PATTERN
+else
+	pid="$(pgrep $PATTERN)"
+fi
+if [ $( echo "$pid" | wc -w ) -gt 1 ]; then
+	#pid=$( echo -n $pid | head -n1 )
+	pid=$(echo -n $pid | awk '{print $1}' )
+	echo "$(basename $0) warn: more then one PID found matching $PATTERN, using the first: $pid" >&2
+	exit 0
+elif [ -z "$pid" ] || [ ! -d "/proc/$pid" ]; then
+	echo "$(basename $0) error: process not found: $1" >&2
+	exit 1
+fi
+
+if [ "$1" = "-s" ] ; then
+	# code from http://stackoverflow.com/questions/205064/is-there-a-way-to-change-another-processs-environment-variables https://gist.github.com/coderofsalvation/e1376e4d2b29607431df
+	echo "$(basename $0) warn: adding $2 in $PATTERN environment..." >&2
+	#sudo 
+	gdb -q -batch -ex "attach $PID" -ex "call putenv(\"$2\")" -ex 'detach' 
+	 # -batch-silent
+	exit $?
+fi
+#else
+# parse "/proc/$PID/environ"
+#  http://stackoverflow.com/questions/3569784/using-sed-to-get-an-env-var-from-proc-environ-weirdness-with-x00
+xargs -n 1 -0 < "/proc/$PID/environ"
diff --git a/bin/power b/bin/power
--- a/bin/power
+++ b/bin/power
@@ -1,1 +1,460 @@
-../../../bin/power
+#!/bin/sh
+
+# used for RGB LEDs
+DEFAULT_LED_COLOR=00FF00
+#  TODO: replace with device names  https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/2854
+OPEN_RGB_KEYBOARD_DEVICE_ID=0
+OPEN_RGB_MOUSE_DEVICE_ID=1
+#OPEN_RGB_MOUSE_ID=$(openrgb -l | grep ...)
+# used for razer keyboards
+OPENRAZER_BASE_PATH=/sys/bus/hid/drivers/razerkbd
+
+# Windows detection
+if grep -i -q 'Microsoft\|Cygwin' /proc/version; then
+	cmd.exe /C power "$@"
+	exit $?
+fi
+
+# TODO: more android cmds: turn off/on wifi, monitor
+
+# check args
+if [ "$1" = "on" ] || [ "$1" = "up" ] || [ "$1" = "off" ] || [ "$1" = "down" ] || [ "$1" = "status" ] || [ "$1" = "check" ]; then
+	CMD=$1
+	TARGET=$2
+elif [ "$2" = "on" ] || [ "$2" = "up" ] || [ "$2" = "off" ] || [ "$2" = "down" ] || [ "$2" = "status" ] || [ "$2" = "check" ]; then
+	CMD=$2
+	TARGET=$1
+fi
+#else continue
+
+case "$CMD" in
+status|check )
+	case "$TARGET" in
+		""|all )
+			findnearby
+			exit 0
+			
+			#OLD:
+			[ -z "$IFACE" ] && IFACE=$( route | grep '^default' | grep -o '[^ ]*$' | head -n1 )
+			MYIP=$( ip -f inet -o addr show dev $IFACE | cut -d\  -f 7 | cut -d/ -f 1 | tail -n1 )
+			[ -z "$MYIP" ] && MYIP=$( ifconfig $IFACE | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}' )
+			
+			echo "$(basename $0): this computer IP is: $MYIP"
+			
+			# ping 10 IPs in (MYIP-5 ; MYIP+5 range)
+			BASEADDR=$( echo -n $MYIP | cut -d. -f 1-3 )
+			VARADDR=$( echo -n $MYIP | cut -d. -f 4 )
+			VARADDRMIN=$( expr $VARADDR - 5 )
+			VARADDRMAX=$( expr $VARADDR + 5 )
+			
+			#for var in $(seq $VARADDRMIN $VARADDRMAX); do
+			#	[ "$MYIP" = "$BASEADDR$var" ] && continue
+			#	
+			#	# ALTERNATIVEs: nmap -sn | nmap --script broadcast-ping
+			#	echo -n "$(basename $0): pinging $BASEADDR.$var... "
+			#	sudo ping -c 1 -W 2 $BASEADDR.$var >/dev/null
+			#	if [ $? -eq 0 ]; then
+			#		# host is online, do further scans
+			#		echo "PONG"
+			#		
+			#		# look for opened ports and try to identify the OS
+			#		#tput setaf 1  # set the red color
+			#		sudo nmap $BASEADDR.$var -F -O -oG - | grep OS
+			#		# http://nmap.org/book/man-host-discovery.html
+			#		#tput sgr0  # back to normal color
+			#		
+			#		# get the MAC address
+			#		#sudo nmap -sP -n $BASEADDR.$var | grep MAC
+			#	fi
+			#	echo
+			#done
+			#echo "$(basename $0): tip: for more infos use nmap -O IPADDR"
+			
+			echo
+			
+			# find DNS names using dig from the "dnsutils" package
+			#dig -t axfr 
+			# find DNS names using dig from the "bind9utils" package
+			# rndc dumpdb -zones
+			
+			echo "$(basename $0): zeroconf/mDNS/Bonjour names scan:"
+			avahi-browse -a --ignore-local --terminate #--parsable 
+			[ $? -ne 0 ] && mdns-scan
+			[ $? -ne 0 ] && nmap --script=broadcast-dns-service-discovery 192.168.1.*
+
+			echo
+			
+			# discover WebServices using https://pypi.org/project/WSDiscovery/
+			echo "$(basename $0): WS-Discovery scan:"
+			wsdiscover
+			
+			echo
+			
+			echo "$(basename $0): NetBIOS scan:"
+			sudo nbtscan -q ${BASEADDR}.1/16
+			[ $? -ne 0 ] && nmap --script smb-os-discovery -p 445 ${BASEADDR}.1.*  #-v
+			#nmblookup -A $BASEADDR*
+
+			echo
+						
+			echo "$(basename $0): ARP scan:"  # https://www.linux-magazine.com/Online/Features/Using-ARP-for-Network-Recon
+			# TIP: get sanitized IEEE OUI Data here https://linuxnet.ca/ieee/oui/
+			sudo arp-scan --localnet  # --quiet 
+			echo "arp:"
+			arp -i $IFACE  # no root req., best executed AFTER arp-scan? https://unix.stackexchange.com/questions/188367/get-names-of-devices-on-the-network
+			
+			#echo "$(basename $0): netdiscover scan:"  # 2FIX: slower than arp-scan?
+			#sudo netdiscover -f -P
+
+			echo
+			
+			echo "$(basename $0): quick nmap OS scan:" # https://serverfault.com/questions/522596/ping-only-os-detection-with-nmap
+			nmap -p 22,80,445,65123,56123 -T5 -A 192.168.1.* --open  # --host-timeout 1s
+			# NO? sudo nmap -sn -O 192.168.1.*  # -sn: Ping Scan - disable port scan
+			[ $? -ne 0 ] && 
+			[ $? -ne 0 ] && ip neigh #| grep REACHABLE | cut -d' ' -f1 | ...
+			
+			echo
+
+			exit 0
+		;;
+
+		powerline )
+			broadlink_cli $BROADLINK_SP2_PARAMS --check
+			echo -n "energy consumption from device (in W): "
+			broadlink_cli $BROADLINK_SP2_PARAMS --energy
+			exit $?
+		;;
+			
+		* ) # default case
+			TARGET=$2
+			ping -c 3 $TARGET
+			[ $? -eq 0 ] && exit 0
+			# try again with zeroconf
+			ping -c 3 $TARGET.local
+			exit $?
+		;;
+	esac
+;;
+
+off|down )  # OFF COMMANDS
+	case "$TARGET" in
+		""|this|me ) # empty string
+			echo "$(basename $0): about to power off this computer"
+			if [ ! -z "$ANDROID_ROOT" ]; then
+				svc power shutdown
+				exit $?
+			fi
+			# echo "Press [ENTER] to continue or ctrl-c to cancel"
+			# sudo poweroff
+			echo "$(basename $0): type 'ok' and press Enter to continue"
+			read REPLY ; [ "$REPLY" = "ok" ] && sudo poweroff
+			echo "$(basename $0): power off cancelled"
+			exit $?
+		;;
+		
+		monitor|screen )
+			echo "$(basename $0): about to power off the monitor"
+			#if [ "$(hostname)" = "BOSS2" ] || [ "$(hostname)" = "BOSS3" ]; then
+				#lgtv_serial poweroff
+				#irsend SEND_ONCE LG_AKB72915207 KEY_POWER
+				#sendir lg_power
+			#fi
+			if [ ! -z "$ANDROID_ROOT" ]; then
+				# input keyevent 26
+				input keyevent KEYCODE_POWER
+				exit $?
+			fi
+			# using HDMI-CEC
+			echo "standby 0" | cec-client -s
+			# using the DDC/CI protocol (may need to change the dev address, check "sudo ddccontrol -p") https://superuser.com/questions/648805/is-it-possible-to-power-on-off-a-monitor-using-the-computer
+			sudo ddccontrol -r 0xe1 -w 0 dev:/dev/i2c-2
+			#ddcutil setvcp d6 5
+			xset dpms force off
+			exit $?
+		;;
+
+		lan|eth*|wifi|wlan* )
+			if [ ! -z "$ANDROID_ROOT" ]; then
+				termux-wifi-enable false
+				[ $? -eq 0 ] && exit 0
+				svc wifi disable
+				[ $? -eq 0 ] && exit 0
+				settings put global wifi_on 0
+				[ $? -eq 0 ] && exit 0
+			fi
+			IFACE=$2
+			[ "$2" = "lan" ] && IFACE=eth0
+			[ "$2" = "wifi" ] && IFACE=wlan0
+			[ "$2" = "wifi" ] && [ "$(hostname)" = "BOSS2" ] && IFACE=wlxc04a0011cfa4
+			# TODO: detect current active interface?
+			echo "$(basename $0): about to power off the network interface: $IFACE"
+			sudo ip link set dev $IFACE down
+			[ $? -eq 0 ] && exit 0
+			sudo ifdown $IFACE
+			[ $? -eq 0 ] && exit 0
+			sudo ifconfig $IFACE down
+			exit $?
+		;;
+
+		bluetooth|bt )
+			if [ ! -z "$ANDROID_ROOT" ]; then
+				svc bluetooth disable
+				settings put global bluetooth_on 0
+				settings put global bluetooth_disabled_profiles 0
+				exit $?
+			fi
+			rfkill block bluetooth
+			sudo hciconfig hci0 down
+			hciconfig
+			exit $?
+		;;
+
+		smartplug )
+			broadlink_cli $BROADLINK_SP2_PARAMS  --turnoff
+			exit $?
+		;;
+			
+		*sd*|*hd* )
+			[ -b "/dev/$2" ] && TARGET=/dev/$2
+			echo "$(basename $0): about to power off the storage device: $TARGET"
+			# using udisksctl
+			sudo udisksctl unmount -b $TARGET
+			sudo udisksctl power-off -b $TARGET
+			# using udisks  http://superuser.com/questions/430438/powering-down-external-hard-drive-flash-drive-etc-using-the-command-line-in-li
+			udisks --unmount $TARGET
+			udisks --detach $TARGET
+			# using hdparam 
+			#sudo hdparm -Y $TARGET
+			# using eject  http://stackoverflow.com/questions/13224509/linux-ubuntu-safely-remove-usb-flash-disk-via-command-line
+			#eject $TARGET
+			[ $? -eq 0 ] && exit 0
+			exit $?
+		;;
+				
+		usb* )
+			echo "$(basename $0): about to power off the USB port: $TARGET"
+			sudo uhubctl -a off -p $TARGET -r 2 -w 2000  # of PICCIOTTO3: -l 2-6
+			exit $?
+		;;
+			
+		keyboard* )
+			openrgb --device "$OPEN_RGB_KEYBOARD_DEVICE_ID" --mode off
+			#OLD: [ -e "$OPENRAZER_BASE_PATH" ] && echo -n "1" > $OPENRAZER_BASE_PATH/matrix_effect_none
+			[ -e "$OPENRAZER_BASE_PATH" ] && razer-cli -e none
+			exit $?
+		;;
+			
+		mouse* )
+			openrgb --device "$OPEN_RGB_MOUSE_DEVICE_ID" --mode static --color 000000
+			exit $?
+		;;
+		
+		* ) # default case
+			# power off a device via an IR blaster (must be configured separately)
+			echo "$(basename $0): about to power off via IR blaster: $TARGET"
+			[ "$TARGET" = LG ] && TARGET=LG_AKB72915207
+			irsend SEND_ONCE $TARGET KEY_POWER
+			
+			#[ $? -eq 0 ] && exit 0
+			#TODO: use cec-client to control more devices?
+			
+			# else try to power off a remote machine (via the passed IP or network name)...
+			echo "$(basename $0): about to power off remote machine: $TARGET"
+			# some computer aliases with fixed IPs associated
+			[ "$2" = "boss3" ] && TARGET=192.168.42.79
+			# check if target machine is connectable
+			sudo ping -c 1 -W 2 $TARGET >/dev/null
+			if [ $? -ne 0 ]; then
+				# try names resolving with with mDNS
+				TARGET=$(nmblookup $TARGET | cut -d' ' -f1)
+				[ "$TARGET" = "name_query" ] && TARGET=$(avahi-resolve --name $TARGET)
+				if [ -z "$TARGET" ]; then
+					echo "$(basename $0): error: target is not connectable: $TARGET" >&2
+					exit 1
+				else
+					echo "$(basename $0): target IP address found: $TARGET" >&2
+				fi
+			fi
+			# ...running Windows
+			# using samba net command http://lifehacker.com/5275652/shut-down-your-windows-pc-remotely-from-linux
+			# TODO: ask username via user input?
+			net rpc shutdown -I $TARGET -U Administrator -f
+			[ $? -eq 0 ] && exit 0
+			# using winexe  https://sourceforge.net/projects/winexe/
+			winexe //$TARGET 'shutdown -s -f'
+			[ $? -eq 0 ] && exit 0
+			# TODO: more windows alternatives
+			# else try remote ssh host on linux
+			ssh -t $TARGET 'poweroff'
+			[ $? -eq 0 ] && exit 0
+			ssh -t $TARGET.local 'poweroff'
+			[ $? -eq 0 ] && exit 0
+			ssh -t TARGET 'shutdown -h now'
+			[ $? -eq 0 ] && exit 0
+			# remote ssh host on Windows
+			ssh $TARGET 'shutdown -s -f'
+			[ $? -eq 0 ] && exit 0
+			# try with Intel AMT tool
+			amttool $TARGET powerdown
+			[ $? -eq 0 ] && exit 0
+			# try with IPMI
+			ipmitool -H $TARGET -v -I lanplus -U ADMIN chassis power off
+			# else
+			echo "$(basename $0): error: no tool found to power off $TARGET" >&2
+			exit 127
+		;;
+	esac
+;;
+
+on|up ) # ON COMMANDS
+	case "$TARGET" in
+		"" ) # empty string
+			echo "$(basename $0) error: no target specified" >&2
+			exit 1
+		;;
+		
+		monitor|screen|lcd )
+			echo "$(basename $0): about to power on the monitor"
+			if [ "$(hostname)" = "BOSS2" ] || [ "$(hostname)" = "BOSS3" ]; then
+				lgtv_serial poweron
+				irsend SEND_ONCE LG_AKB72915207 KEY_POWER
+				sendir lg_power
+			fi
+			if [ ! -z "$ANDROID_ROOT" ]; then
+				input keyevent KEYCODE_WAKEUP
+				exit $?
+			fi
+			# try using HDMI-CEC
+			echo "on 0" | cec-client -s
+			# try using the DDC/CI protocol (may need to change the dev address, check "sudo ddccontrol -p")  https://superuser.com/questions/648805/is-it-possible-to-power-on-off-a-monitor-using-the-computer
+			sudo ddccontrol -r 0xe1 -w 1 dev:/dev/i2c-2
+			#ddcutil setvcp d6 1
+			xset dpms force on
+			exit $?
+		;;
+
+		lan|wifi|eth*|wlan* )
+			if [ ! -z "$ANDROID_ROOT" ]; then
+				termux-wifi-enable true
+				[ $? -eq 0 ] && exit 0
+				svc wifi enable
+				[ $? -eq 0 ] && exit 0
+				settings put global wifi_on 1
+				exit $?
+			fi
+			IFACE=$2
+			[ "$2" = "lan" ] && IFACE=eth0
+			[ "$2" = "wifi" ] && IFACE=wlan0
+			[ "$2" = "wifi" ] && [ "$(hostname)" = "BOSS2" ] && IFACE=wlxc04a0011cfa4
+			# TODO: detect current active interface?
+			echo "$(basename $0): about to power on the network interface: $IFACE"
+			sudo ip link set dev $IFACE up
+			[ $? -eq 0 ] && exit 0
+			sudo ifup $IFACE
+			[ $? -eq 0 ] && exit 0
+			sudo ifconfig $IFACE up
+			[ $? -eq 0 ] && exit 0
+			# TOFIX: wifi may need to be reinitialized with wpa_supplicant?
+			exit $?
+		;;
+		
+		bluetooth|bt )
+			if [ ! -z "$ANDROID_ROOT" ]; then
+				svc bluetooth enable
+				settings put global bluetooth_on 1
+				settings put global bluetooth_disabled_profiles 1
+				exit $?
+			fi
+			service bluetooth start
+			systemctl start bluetooth
+			rfkill unblock bluetooth
+			# TODO: bt-device --set Powered 1
+			sudo hciconfig hci0 up
+			hciconfig
+			exit $?
+		;;
+		
+		smartplug )
+			broadlink_cli $BROADLINK_SP2_PARAMS  --turnon
+			exit $?
+		;;
+
+		usb* )
+			echo "$(basename $0): about to power on the USB port: $TARGET"
+			sudo uhubctl -a on -p $TARGET  # on PICCIOTTO3: -l 2-6
+			exit $?
+		;;
+		
+		razer*|keyboard )
+			openrgb --device "$OPEN_RGB_KEYBOARD_DEVICE_ID" --mode static --color $DEFAULT_LED_COLOR   # TODO: set brightness
+			if [ -e "$OPENRAZER_BASE_PATH" ]; then
+				#echo -n "1" > $OPENRAZER_BASE_PATH/matrix_effect_spectrum
+				#echo -n "20" >  $OPENRAZER_BASE_PATH/matrix_brightness
+				razer-cli -v --effect static  # effect
+				razer-cli -v --color $DEFAULT_LED_COLOR
+				razer-cli -v --brightness 10
+				razer-cli -v --sync  # sync lighting effects to all supported Razer products
+			fi
+			exit $?
+			;;
+
+		mouse* )
+			openrgb --device "$OPEN_RGB_MOUSE_DEVICE_ID" --mode static --color $DEFAULT_LED_COLOR  # TODO: set brightness
+			exit $?
+			;;
+
+		* ) # default case
+			# power on a device via an IR blaster (must be configured separately)
+			#echo "$(basename $0): about to power on via IR blaster: $TARGET"
+			#irsend SEND_ONCE $TARGET KEY_POWER
+			#[ $? -eq 0 ] && exit 0
+			#TODO: use cec-client to control more devices?
+
+			# else try to wake up a remote machine (via the passed IP or network name)
+			echo "$(basename $0): about to wake up remote machine: $TARGET"
+			# via wakeonlan perl script  
+			wakeonlan -i $TARGET
+			[ $? -eq 0 ] && exit 0
+			# search the target MAC address in a db file (should have at least 2 columns: MAC Address,hostname)
+			MAC_DB=$PENDRIVE/Documents/db/mynicmac.csv
+			[ -f $MAC_DB ] && TARGET_MAC=$(grep $TARGET, $MAC_DB | cut -f1 -d,)
+			# else target MAC addr must be passed as 2nd arg
+			[ ! -f $MAC_DB ] && TARGET_MAC=$2
+			powerwake $TARGET_MAC
+			[ $? -eq 0 ] && exit 0
+			etherwake $TARGET_MAC
+			[ $? -eq 0 ] && exit 0
+			wol $TARGET_MAC
+			[ $? -eq 0 ] && exit 0
+			# python oneliner from https://www.mythtv.org/wiki/Wake-on-LAN
+			echo "$(basename $0): broadcasting magic packet targeting $TARGET_MAC..."
+			#python2 -c "print('broadcasting magic packet to ' + r'\x'+\"$TARGET_MAC\".replace(':',r'\x') + '...' );"
+			python -c "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_DGRAM); s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1); s.sendto('\xff'*6+(r'\x'+\"$TARGET_MAC\".replace(':',r'\x'))*16, ('<broadcast>', 7));"
+			[ $? -eq 0 ] && exit 0
+			# try with Intel AMT tool
+			amttool $TARGET powerup
+			[ $? -eq 0 ] && exit 0
+			# try with IPMI
+			ipmitool -H $TARGET -v -I lanplus -U ADMIN chassis power on
+			# else
+			echo "$(basename $0): error: no tool found to power on $TARGET" >&2
+			exit 127
+		;;
+	esac
+;;
+esac
+
+# else
+echo "usage: $(basename $0) on|off|status [monitor|hostname|all|mac_addr|lirc_remote|device]"
+echo "examples:"
+echo "  power off monitor"
+echo "  power off wifi"
+echo "  power off /dev/sdb"
+echo "  power off 192.168.0.3"
+echo "  power status 192.168.0.3"
+echo "  power status all"
+echo "  power on 00:41:F5:A1:3A:8D"
+echo "  power on HIFI"
+echo
+exit 0
diff --git a/bin/psinfo b/bin/psinfo
--- a/bin/psinfo
+++ b/bin/psinfo
@@ -1,1 +1,63 @@
-../../../bin/psinfo
+#!/bin/sh
+
+if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) PPID|PATTERN"
+	echo
+	exit 0
+fi
+
+PATTERN="$1"
+
+#pid=$(ps ax | grep $PATTERN | grep -v grep | cut -f2 -d " ")
+# safer alternative using pgrep (in busybox)
+if [ -d "/proc/$PATTERN" ]; then
+	pid=$PATTERN
+else
+	pid="$(pgrep $PATTERN)"
+fi
+if [ $( echo "$pid" | wc -w ) -gt 1 ]; then
+	#pid=$( echo -n $pid | head -n1 )
+	pid=$(echo -n $pid | awk '{print $1}' )
+	echo "$(basename $0) warn: more then one PID found matching $PATTERN, using the first: $pid" >&2
+elif [ -z "$pid" ] || [ ! -d "/proc/$pid" ]; then
+	echo "$(basename $0) error: process not found: $1" >&2
+	exit 1
+fi
+
+#PS_FORMAT=pid,command,args
+
+echo
+
+pstree -p $pid
+
+echo
+
+# MEMO: /proc/$pid/maps shows memory regions + loaded shared libs
+echo "$(basename $0): loaded shared libs:"
+cat /proc/$pid/maps | grep lib | cut -d/ -f2- | uniq
+
+echo
+
+echo "$(basename $0): process status infos: "
+# MEMO: extracted from /proc/$pid/stat
+echo_ps_stat() {
+	ps -A -o pid,$1 | grep $pid | cut -d" "  -f2-
+}
+echo -n "user: "  ; echo_ps_stat user
+echo -n "group: "  ; echo_ps_stat group
+echo -n "PPID: "  ; echo_ps_stat ppid
+echo -n "cmdline args: "  ; echo_ps_stat args
+echo -n "elapsed time: "  ; echo_ps_stat etime
+echo -n "status: "  ; echo_ps_stat stat
+echo -n "virtual memory size (in KiB): "  ; echo_ps_stat vsz
+echo -n "resident set size (non-swapped phys memory used): "  ; echo_ps_stat rss
+echo -n "tty: "  ; echo_ps_stat tty
+
+echo
+
+# start a realtime monitor, shows io trasfer status:
+# showspeed in perl https://github.com/jnweiger/showspeed
+#showspeed $1
+#  https://github.com/dspinellis/pmonitor
+#pmonitor -p $pid
+top -b | grep $pid
diff --git a/bin/swap b/bin/swap
--- a/bin/swap
+++ b/bin/swap
@@ -1,1 +1,26 @@
-../../../bin/swap
+#!/bin/sh
+ 
+command -p swap "$@"  2> /dev/null
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+# else alternative shell script
+# args checking
+if [ "$#" -lt 2 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) FILE1 FILE2"
+	echo
+	exit 0
+elif [ ! -f "$1" ]; then
+	echo "$(basename $0) error: file does not exist: $1" >&2
+	exit 1
+elif [ ! -f "$2" ]; then
+	echo "$(basename $0) error: file does not exist: $2" >&2
+	exit 1
+fi
+[ "$#" -gt 2 ] && echo "$(basename $0) warn: more than 2 args passed, skipping after the second" >&2
+
+echo "$(basename $0): \`$1' <-> \`$2'"
+
+TMPFILE="$(dirname "$1")/.$$.tmp"
+mv -n "$1" "$TMPFILE"
+mv -n "$2" "$1"
+mv -n "$TMPFILE" "$2"
diff --git a/bin/units b/bin/units
--- a/bin/units
+++ b/bin/units
@@ -1,1 +1,118 @@
-../../../bin/units
+#!/bin/sh
+
+# uppercase currencies
+# TODO: define aliases instead? https://www.gnu.org/software/units/manual/html_node/Defining-Unit-List-Aliases.html
+INPUT="$@"
+INPUT=$(echo "$INPUT" | sed 's/usd/USD/')
+INPUT=$(echo "$INPUT" | sed 's/eur/EUR/')
+INPUT=$(echo "$INPUT" | sed 's/gbp/GBP/')
+
+command -p units --history '' -v -1  "$INPUT"  # --compact
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+qalc "$1 to $2"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+# MORE ALTERNATIVEs: convertall, gonvert, units.pl
+
+# pure shell-script alternative follow
+if [ "$#" -lt 2 ] || [ "$#" -gt 2 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) QUANTITYfrom to"
+	echo
+	exit 0
+fi
+
+UNIT="" # global variable used as function return value
+get_unit_simbol() {
+	# handle some unit aliases
+	# TODO: try parsing units.dat for more aliases
+	UNIT=$1
+	case $1 in
+		in) UNIT="inch" ;;
+		inches) UNIT="inch" ;;
+		oz) UNIT="oz" ;;
+		ounces) UNIT="oz" ;;
+		gr) UNIT="g" ;;
+		grams) UNIT="g" ;;
+		lbs) UNIT="pound" ;;
+		lb) UNIT="pound" ;;
+		km) UNIT="km" ; return ;;
+		km) UNIT="km" ; return ;;
+		kg) UNIT="kg" ; return ;;
+		foot) UNIT="ft" ;;
+		yard) UNIT="yd" ;;
+		USD) UNIT="usd" ;;
+		$) UNIT="usd" ;;
+		EUR) UNIT="eur" ;;
+		euro) UNIT="eur" ;;
+		€) UNIT="eur" ;;
+		£) UNIT="gbp" ;;
+		g) UNIT="gram" ;;
+		# TODO: more aliases
+	esac
+}
+
+INPUT_VALUE="$( echo -n $1 | egrep -o '^[0-9.]+' )"
+INPUT_UNIT="$( echo -n $1 | sed -e s/^$INPUT_VALUE//g  )"
+
+get_unit_simbol $INPUT_UNIT
+INPUT_UNIT=$UNIT
+
+get_unit_simbol $2
+TARGET_UNIT=$UNIT
+
+# using python+SymPy  http://stackoverflow.com/questions/1025145/units-conversion-in-python
+RESULT=$(python -c "from sympy.physics import units; print('%g' % (float($INPUT_VALUE) * units.$INPUT_UNIT / units.$TARGET_UNIT) )")
+
+# TODO: SciPy alternative
+
+if [ $? -ne 0 ]; then
+	#else builtin units converter using awk
+	# TODO: better submutiples handling by detecting SI units   http://stackoverflow.com/questions/32091117/simple-unit-converter-in-python
+	[ "$INPUT_UNIT" = "cm" ] && [ "$TARGET_UNIT" = "inch" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE / 2.54 }")
+	[ "$INPUT_UNIT" = "inch" ] && [ "$TARGET_UNIT" = "cm" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE * 2.54 }")
+	[ "$INPUT_UNIT" = "inch" ] && [ "$TARGET_UNIT" = "mm" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE * 25.4 }")
+	[ "$INPUT_UNIT" = "oz" ] && [ "$TARGET_UNIT" = "g" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE * 28.349523125 }")
+	[ "$INPUT_UNIT" = "oz" ] && [ "$TARGET_UNIT" = "kg" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE * 28.349523125 / 1000 }")
+	[ "$INPUT_UNIT" = "g" ] && [ "$TARGET_UNIT" = "oz" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE / 28.349523125 }")
+	[ "$INPUT_UNIT" = "kg" ] && [ "$TARGET_UNIT" = "oz" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE * 1000 / 28.349523125 }")
+	[ "$INPUT_UNIT" = "pound" ] && [ "$TARGET_UNIT" = "g" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE * 453.59237 }")
+	[ "$INPUT_UNIT" = "pound" ] && [ "$TARGET_UNIT" = "kg" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE * 0.4535924 }")
+	[ "$INPUT_UNIT" = "kg" ] && [ "$TARGET_UNIT" = "pound" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE / 0.4535924 }")
+	[ "$INPUT_UNIT" = "mile" ] && [ "$TARGET_UNIT" = "km" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE * 1.609347 }")
+	[ "$INPUT_UNIT" = "km" ] && [ "$TARGET_UNIT" = "mile" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE / 1.609347 }")
+	[ "$INPUT_UNIT" = "ft" ] && [ "$TARGET_UNIT" = "cm" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE * 30.48 }")
+	[ "$INPUT_UNIT" = "ft" ] && [ "$TARGET_UNIT" = "m" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE * 0.3048 }")
+	[ "$INPUT_UNIT" = "cm" ] && [ "$TARGET_UNIT" = "ft" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE / 30.48 }")
+	[ "$INPUT_UNIT" = "yd" ] && [ "$TARGET_UNIT" = "m" ] && RESULT=$(awk "BEGIN { printf \"%g\", $INPUT_VALUE * 0.9144 }")
+	# ...  http://www.wsdot.wa.gov/Reference/metrics/factors.htm
+	# TODO: gal->l
+	# TODO: awg->mm (awg is missing in sympy?)
+	# TODO: kelvin<->celsius
+	# TODO: cal<->Joule (cal is missing in sympy?)
+	# TODO: Pa<->bar
+	# TODO: knot (nodo) -> 1kn = 1M/h = 1.852km/h
+	# ... (see also: units.dat)
+fi
+
+# money rates -> convert using google
+case $INPUT_UNIT in
+	usd|eur|gbp|$|USD|EUR|GBP )
+	wget -q -O - "https://www.google.com/finance/converter?a=$INPUT_VALUE&from=$INPUT_UNIT&to=$TARGET_UNIT" | sed -e 's/<[^>]*>//g; /^[ \t]*$/d' | tail -n1
+	echo
+	exit 0
+	;;
+esac
+
+# TODO: alternatives using REST APIs
+# https://www.boxcontrol.net/write-simple-currency-converter-in-python.html
+
+if [ -z "$RESULT" ]; then
+	# TODO: try google online conversion
+	echo "$(basename $0): unsupported conversion unit(s): $*" >&2
+	exit 1
+fi
+
+echo " $INPUT_VALUE $INPUT_UNIT = $RESULT $TARGET_UNIT"
+echo
+exit 0
diff --git a/bin/usbreset b/bin/usbreset
--- a/bin/usbreset
+++ b/bin/usbreset
@@ -1,1 +1,51 @@
-../../../bin/usbreset
+#!/bin/sh
+
+#command -p usbreset "$@"
+#_ES=$? ; [ $_ES -ne 127 ] && exit $_ES 
+
+# args checking
+if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+	echo "usage: $(basename $0) [USB_BUS:USB:DEV]"
+	echo
+	echo "will reset ALL USB ports if no one specified."
+	echo "tip: check USB ports addresses with the lsusb command"
+	exit 0
+fi
+
+if [ ! -e "$1" ]; then
+	echo "$(basename $0): about to reset ALL USB ports"
+	echo "$(basename $0): type 'ok' and press Enter to continue"
+	read
+	if [ "$REPLY" != "ok" ]; then
+		echo "$(basename $0): reset cancelled"
+		exit 1
+	fi
+
+	# http://askubuntu.com/a/290519
+	# TODO: check mounted usb mass storage devices
+	for i in $(ls /sys/bus/pci/drivers/ehci_hcd/|grep :)
+		do echo $i >/sys/bus/pci/drivers/ehci_hcd/unbind
+		echo $i >/sys/bus/pci/drivers/ehci_hcd/bind
+	done
+	for i in $(ls /sys/bus/pci/drivers/xhci_hcd/|grep :)
+		do echo $i >/sys/bus/pci/drivers/xhci_hcd/unbind
+		echo $i >/sys/bus/pci/drivers/xhci_hcd/bind
+	done
+
+	exit 0
+fi
+
+# else reset a single port
+echo "$(basename $0): about to reset the USB port $1"
+echo "$(basename $0): Press any key to continue or Ctrl-C to abort... "; read -s -n 1
+
+#sudo sh -c "echo 1 > /sys/bus/usb/drivers/usb/$1/remove"
+
+sudo sh -c "echo 0 > /sys/bus/usb/devices/$1/authorized"
+sudo sh -c "echo 1 > /sys/bus/usb/devices/$1/authorized"
+
+#	... http://billauer.co.il/blog/2013/02/usb-reset-ehci-uhci-linux/
+#	... http://www.linux.org/threads/resetting-the-usb-subsystem.6256/
+#	... http://askubuntu.com/questions/645/how-do-you-reset-a-usb-device-from-the-command-line
+
+exit 0
diff --git a/bin/usftpd b/bin/usftpd
--- a/bin/usftpd
+++ b/bin/usftpd
@@ -1,1 +1,24 @@
-../../../bin/usftpd
+#!/bin/sh
+
+#command -p usftpd "$@"
+#_ES=$? ; [ $_ES -ne 127 ] && exit $_ES 
+
+DIR_SERVED="$PWD"
+[ ! -z "$1" ] && DIR_SERVED="$1"
+cd "$DIR_SERVED"
+
+PORT=2022 
+
+_MYIP=$( ip -f inet -o addr show dev $IFACE | cut -d\  -f 7 | cut -d/ -f 1 | tail -n1 )
+_HOSTNAME=$(hostname)  # $HOSTNAME envvar is only defined in bash
+echo "$(basename $0): serving $DIR_SERVED at sftp://$_MYIP/ or sftp://${_HOSTNAME}.local/"
+echo "$(basename $0): press CTRL+C to abort"
+
+# using rclone https://rclone.org/commands/rclone_serve_sftp/
+rclone serve sftp --addr :$PORT "$DIR_SERVED" --no-auth
+[ $? -eq 0 ] && exit 0
+
+# TODO: more alternatives
+
+#else
+exit 127
diff --git a/bin/zerofree b/bin/zerofree
--- a/bin/zerofree
+++ b/bin/zerofree
@@ -1,1 +1,26 @@
-../../../bin/zerofree
+#!/bin/sh
+
+# using sfill from secure-delete
+command -p sfill -llz "$@"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+zerofree "$@"
+_ES=$? ; [ $_ES -ne 127 ] && exit $_ES
+
+# alternative using dd (1 pass)
+if [ ! -d "$1" ]; then
+	echo "$(basename $0) error: dir does not exist: $1" >&2
+	exit 1
+fi
+
+# ask interactive confirmation
+echo "$(basename $0): about to zerofill freespace on \"$1\""
+echo "$(basename $0): press Enter to continue or Ctrl-C to abort... "
+read
+
+#dd if=/dev/zero of="$1/filler" bs=10M
+dd if=/dev/zero of="$1/filler" bs=10485760
+dd if=/dev/zero of="$1/filler1" bs=1
+
+rm $1/filler
+rm $1/filler1
