scripted commit

diff --git a/bin/power b/bin/power
--- a/bin/power
+++ b/bin/power
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # used for RGB LEDs
 DEFAULT_LED_COLOR=00FF00
@@ -9,6 +9,8 @@ OPEN_RGB_MOUSE_DEVICE_ID=1
 # used for razer keyboards
 OPENRAZER_BASE_PATH=/sys/bus/hid/drivers/razerkbd
 
+MY_ROUTER_ADDR_LIST=("192.168.42.1"  "192.168.1.138"  "192.168.2.1"  "DietPi.local"  "friendlywrt.local")
+
 # Windows detection
 if grep -i -q 'Microsoft\|Cygwin' /proc/version; then
 	cmd.exe /C power "$@"
@@ -18,14 +20,19 @@ fi
 # TODO: more android cmds: turn off/on wifi, monitor
 
 # check args
-if [ "$1" = "on" ] || [ "$1" = "up" ] || [ "$1" = "off" ] || [ "$1" = "down" ] || [ "$1" = "status" ] || [ "$1" = "check" ]; then
-	CMD=$1
-	TARGET=$2
-elif [ "$2" = "on" ] || [ "$2" = "up" ] || [ "$2" = "off" ] || [ "$2" = "down" ] || [ "$2" = "status" ] || [ "$2" = "check" ]; then
-	CMD=$2
-	TARGET=$1
-fi
-#else continue
+case "$1" in
+	on|up|start|off|down|status|check|reboot|cycle|restart )
+		CMD=$1
+		TARGET=$2
+		;;
+esac
+case "$2" in
+	on|up|start|off|down|status|check|reboot|cycle|restart )
+		CMD=$2
+		TARGET=$1
+		;;
+esac
+
 
 case "$CMD" in
 status|check )
@@ -256,14 +263,12 @@ off|down )  # OFF COMMANDS
 		;;
 		
 		*router|*wrt|nanopi|dietpi )
-			#TARGET=$(getip DietPi.local)
-			#[ -z "$TARGET" ] && TARGET=192.168.1.138
 			# remote shutdown
-			ssh -o StrictHostKeyChecking=no root@192.168.1.138 'poweroff'
-			ssh -o StrictHostKeyChecking=no root@DietPi.local 'poweroff'
-			#curl "https://$TARGET/cgi-bin/poweroff"
-			#curl "http://$TARGET:7681/?arg=/sbin/poweroff"
-			#TODO: try with fastweb router fixed ip
+			for addr in ${MY_ROUTER_ADDR_LIST[@]}; do
+				echo "$(basename $0) info: trying ${addr}..." >&2
+				ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=3  root@${addr} 'poweroff'
+				# -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa   https://forum.openwrt.org/t/unable-to-connect-via-ssh-no-matching-host-key-type-found/114430/24
+			done
 			exit $?
 		;;
 		
@@ -459,6 +464,23 @@ on|up ) # ON COMMANDS
 			# else
 			echo "$(basename $0): error: no tool found to power on $TARGET" >&2
 			exit 127
+		;;
+	esac
+;;
+
+cycle|reset|reboot ) # RESET COMMANDS
+	case "$TARGET" in
+		*router|*wrt|nanopi|dietpi )
+			for addr in ${MY_ROUTER_ADDR_LIST[@]}; do
+				echo "$(basename $0) info: trying ${addr}..." >&2
+				ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=3 -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa  root@${addr} 'reboot'
+			done
+			exit $?
+		;;
+		
+		* ) # default case
+			echo "$(basename $0) error: no target specified" >&2
+			exit 1
 		;;
 	esac
 ;;
